/**
 * Item Master frontend contract. NOT a backend schema: the tables, keys and constraints
 * are designed in the separate backend phase. Numeric fields are `number | null` (null =
 * not entered). Values marked "pending" are user-entered: their business formulas are
 * not confirmed (FINAL BUSINESS FORMULA PENDING CONFIRMATION).
 */
import type { IsoDate } from "@/lib/erp/formatting";

export type { IsoDate };

/** How the workspace is showing an item. VIEW is read-only. */
export type ItemMode = "VIEW" | "NEW" | "EDIT" | "CLONE";

/** Record lifecycle in the prototype: a draft, or saved (complete / demo-active). */
export type ItemRecordStatus = "DRAFT" | "SAVED";

export type ItemBasic = {
  productTypeId: string;
  productName: string;
  categoryId: string;
  groupId: string;
  subGroupId: string;
  brandId: string;
  shadeId: string;
  shortDescription: string;
  itemRemark: string;
  /** Meaning not specified yet; kept as entered text. */
  workCut: string;
  createDate: IsoDate;
  /** Meaning not specified yet; kept as entered text. */
  menu: string;
  designGroupId: string;
  isService: boolean;
  primaryUnitId: string;
  secondaryUnitId: string;
  hsnSac: string;
  tax1Pct: number | null;
  tax2Pct: number | null;
  tax3Pct: number | null;
};

/** Customer / party specific name for the same item. */
export type PartyAlias = { id: string; partyId: string; synonym: string };

export type WeftBeam = {
  /** Yarn / product on the beam. */
  productId: string;
  noOfEnds: number | null;
  meter: number | null;
  denier: number | null;
  weightPerPcs: number | null;
  rate: number | null;
  /** Pending: beam cost formula not confirmed; entered by the user. */
  cost: number | null;
};

export type WeftLine = {
  id: string;
  /** Yarn / product. */
  productId: string;
  pick: number | null;
  card: number | null;
  denier: number | null;
  /** Pending formula; entered by the user. */
  perPcsYarn: number | null;
  rate: number | null;
  /** Pending formula; entered by the user. */
  perPcsRate: number | null;
};

export type WeftDetail = {
  groundPick: number | null;
  cut: number | null;
  /** e.g. "48/72" — format not specified; kept as text. */
  widthReed: string;
  reedSpace: number | null;
  /** Item whose weft recipe was (or will be) copied. */
  copyRecipeItemId: string;
  addCutPct: number | null;
  saleRate: number | null;
  otherCost: number | null;
  beam: WeftBeam;
  lines: WeftLine[];
  bomDescription: string;
  /** Pending formulas; entered by the user. */
  pickRate: number | null;
  perPcsYarn: number | null;
  jobRate: number | null;
  netCost: number | null;
};

export type WarpLine = {
  id: string;
  typeId: string;
  productId: string;
  denier: number | null;
  ends: number | null;
  pattern: string;
  patternSeq: string;
  qtyWt: number | null;
  perMtrYarnWt: number | null;
  yarnRate: number | null;
  /** Pending formula; entered by the user. */
  amount: number | null;
};

export type WarpDetail = {
  length: number | null;
  /** Denting (Bharan). */
  denting: string;
  bomDescription: string;
  /** Entered on the form; compared with the sum of line ends. */
  totalBeamEnds: number | null;
  lines: WarpLine[];
  /** Pending formulas; entered by the user. */
  perPcsYarn: number | null;
  netCost: number | null;
};

export type ItemSetup = {
  manageLotNumber: boolean;
  manageQualityControlled: boolean;
  manageContainerControlled: boolean;
  standardBomBeamId: string;
  standardBomId: string;
  ratePct: number | null;
  discountPct: number | null;
  /** Rate 1 … Rate 10. */
  rates: (number | null)[];
  conversion: number | null;
  avgWeight: number | null;
  primaryConversionFactor: number | null;
  multiplier: number | null;
  specialDiscountPct: number | null;
};

export type ItemStatusConfig = {
  productStatusId: string;
  validFrom: IsoDate;
  /** Empty = open-ended validity. */
  validTo: IsoDate | "";
  allowedCompanyIds: string[];
  allowedDepartmentIds: string[];
  allowedProcessIds: string[];
};

/** Browser-memory preview only. ITEM IMAGE STORAGE → BACKEND PHASE. */
export type ItemImage = { name: string; type: string; size: number; url: string };

/** Metadata only; files are not uploaded in the prototype. */
export type ItemAttachment = {
  id: string;
  name: string;
  type: string;
  size: number;
  addedBy: string;
  addedAt: string;
};

/** Everything the user edits. Identity and timestamps come from the service. */
export type ItemInput = {
  basic: ItemBasic;
  partyAliases: PartyAlias[];
  weft: WeftDetail;
  warp: WarpDetail;
  setup: ItemSetup;
  status: ItemStatusConfig;
  image: ItemImage | null;
  attachments: ItemAttachment[];
};

export type ItemRecord = ItemInput & {
  id: string;
  /** Demo code. FINAL ITEM CODE WILL BE GENERATED BY BACKEND. */
  code: string;
  recordStatus: ItemRecordStatus;
  /** Fixture records cannot be deleted; only drafts created in this session can. */
  origin: "fixture" | "session";
  createdAt: string;
  updatedAt: string;
};

/** Register row with display names resolved. */
export type ItemSummary = {
  id: string;
  code: string;
  productName: string;
  productType: string;
  category: string;
  group: string;
  brand: string;
  shade: string;
  hsnSac: string;
  primaryUnit: string;
  productStatus: string;
  recordStatus: ItemRecordStatus;
  origin: ItemRecord["origin"];
  validFrom: IsoDate;
  validTo: IsoDate | "";
  updatedAt: string;
  hasImage: boolean;
};

export type LookupOption = { id: string; code: string; name: string };

export type ItemMasterLookups = {
  productTypes: LookupOption[];
  categories: LookupOption[];
  groups: LookupOption[];
  subGroups: (LookupOption & { groupId: string })[];
  brands: LookupOption[];
  shades: LookupOption[];
  designGroups: LookupOption[];
  uoms: LookupOption[];
  parties: LookupOption[];
  yarns: (LookupOption & { denier: number | null })[];
  warpTypes: LookupOption[];
  standardBomBeams: LookupOption[];
  standardBoms: LookupOption[];
  productStatuses: LookupOption[];
  companies: LookupOption[];
  departments: LookupOption[];
  processes: LookupOption[];
};

/** Field → message. Keys are dotted paths such as "basic.productName". */
export type ItemValidationErrors = Record<string, string>;
