/**
 * ProductionDemoService — FRONTEND DEMO ADAPTER.
 *
 * Implements ProductionService entirely in memory so the Rapier workflows can be reviewed
 * before the backend exists. Nothing is written to Supabase or localStorage; a page reload
 * restores the fixtures. It simulates, and the final backend MUST re-implement atomically
 * inside PostgreSQL transactions:
 *   - yarn issue / return against warehouse stock and the original issue,
 *   - job card received / balance / status from daily production and job card receipts,
 *   - butta cutting and mill issue ↔ receive balances,
 *   - fabric stock transfer (source OUT and destination IN together),
 *   - stock conversion documents with linked stock out / stock in lines.
 * FINAL DOCUMENT NUMBERING WILL BE GENERATED BY BACKEND; the numbers here are demo only.
 */
import type {
  Cutting,
  DailyProduction,
  DailyProductionLineRow,
  DateRange,
  FabricConversion,
  FabricTransfer,
  InputOf,
  IsoDate,
  JobCard,
  JobCardAdjustmentInput,
  JobCardReceipt,
  JobCardRow,
  JobOrder,
  MasterOption,
  OperationalStatus,
  OutwardIssue,
  OutwardIssueRow,
  OutwardProcess,
  OutwardReceipt,
  ProductionDraft,
  ProductionKind,
  ProductionMasters,
  RowOf,
  TraceStage,
  YarnIssue,
  YarnReturn,
} from "@/features/production/types/production";
import {
  ProductionValidationError,
  type CreatedDocument,
  type ProductionService,
  type StockQuery,
} from "@/features/production/services/production-service";
import {
  compareQty,
  isPositiveQty,
  lineAmount,
  subtractQty,
  sumAmount,
  sumQty,
} from "@/lib/erp/numbers";
import { formatQty, isIsoDate, isWithinRange } from "@/lib/erp/formatting";
import {
  DEMO_COUNTERS,
  DEMO_FABRIC_STOCK,
  DEMO_MASTERS,
  DEMO_YARN_STOCK,
  demoSeeds,
} from "@/features/production/demo/production-demo-data";

/** Demo document number prefixes. FINAL DOCUMENT NUMBERING WILL BE GENERATED BY BACKEND. */
export const DEMO_NUMBER_PREFIX: Record<ProductionKind, string> = {
  jobOrder: "JCO",
  yarnIssue: "YI",
  yarnReturn: "YR",
  jobCard: "JCI",
  dailyProduction: "DPR",
  jobCardReceipt: "JCR",
  buttaIssue: "BCI",
  buttaReceipt: "BCR",
  millIssue: "MI",
  millReceipt: "MR",
  fabricTransfer: "FST",
  cutting: "CT",
  fabricConversion: "FSC",
};

type DemoState = {
  masters: ProductionMasters;
  yarnStock: Map<string, number>;
  fabricStock: Map<string, number>;
  counters: Record<ProductionKind, number>;
  seq: number;
  jobOrders: JobOrder[];
  yarnIssues: YarnIssue[];
  yarnReturns: YarnReturn[];
  jobCards: JobCard[];
  dailyProductions: DailyProduction[];
  jobCardReceipts: JobCardReceipt[];
  outwardIssues: OutwardIssue[];
  outwardReceipts: OutwardReceipt[];
  fabricTransfers: FabricTransfer[];
  cuttings: Cutting[];
  conversions: FabricConversion[];
  drafts: ProductionDraft[];
};

const OUTWARD: Record<"buttaIssue" | "millIssue" | "buttaReceipt" | "millReceipt", OutwardProcess> =
  {
    buttaIssue: "butta",
    buttaReceipt: "butta",
    millIssue: "mill",
    millReceipt: "mill",
  };

const fail = (field: string, message: string): never => {
  throw new ProductionValidationError(field, message);
};

function clone<T>(value: T): T {
  return structuredClone(value);
}

function byNewest<T extends { date: IsoDate; number: string }>(a: T, b: T): number {
  return b.date.localeCompare(a.date) || b.number.localeCompare(a.number);
}

export class ProductionDemoService implements ProductionService {
  readonly mode = "demo" as const;
  private state: DemoState;

  constructor(options: { seed?: boolean } = {}) {
    this.state = ProductionDemoService.emptyState();
    if (options.seed !== false) this.applySeeds();
  }

  private static emptyState(): DemoState {
    return {
      masters: clone(DEMO_MASTERS),
      yarnStock: new Map(Object.entries(DEMO_YARN_STOCK)),
      fabricStock: new Map(Object.entries(DEMO_FABRIC_STOCK)),
      counters: { ...DEMO_COUNTERS },
      seq: 0,
      jobOrders: [],
      yarnIssues: [],
      yarnReturns: [],
      jobCards: [],
      dailyProductions: [],
      jobCardReceipts: [],
      outwardIssues: [],
      outwardReceipts: [],
      fabricTransfers: [],
      cuttings: [],
      conversions: [],
      drafts: [],
    };
  }

  /** Restore the fixtures (used by the "Reset demo data" action). */
  reset(): void {
    this.state = ProductionDemoService.emptyState();
    this.applySeeds();
  }

  private applySeeds(): void {
    const created = new Map<ProductionKind, string[]>();
    const resolve = (value: unknown): unknown => {
      if (typeof value === "string" && value.startsWith("ref:")) {
        const [, kind, index] = value.split(":");
        const id = created.get(kind as ProductionKind)?.[Number(index)];
        if (!id) throw new Error(`Unresolved demo seed reference ${value}`);
        return id;
      }
      if (Array.isArray(value)) return value.map(resolve);
      if (value && typeof value === "object") {
        return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolve(v)]));
      }
      return value;
    };
    for (const seed of demoSeeds()) {
      const doc = this.post(seed.kind, resolve(seed.input) as InputOf<typeof seed.kind>);
      created.set(seed.kind, [...(created.get(seed.kind) ?? []), doc.id]);
    }
  }

  // -------------------------------------------------------------------------
  // ProductionService
  // -------------------------------------------------------------------------

  async getMasters(): Promise<ProductionMasters> {
    return clone(this.state.masters);
  }

  async list<K extends ProductionKind>(kind: K, range?: DateRange): Promise<RowOf<K>[]> {
    const rows = this.rows(kind);
    return rows.filter((r) => !range || isWithinRange(r.date, range.from, range.to)).sort(byNewest);
  }

  async create<K extends ProductionKind>(kind: K, input: InputOf<K>): Promise<CreatedDocument> {
    return this.post(kind, clone(input));
  }

  async listDrafts<K extends ProductionKind>(kind: K): Promise<ProductionDraft<K>[]> {
    return clone(this.state.drafts.filter((d): d is ProductionDraft<K> => d.kind === kind));
  }

  async saveDraft<K extends ProductionKind>(
    kind: K,
    input: InputOf<K>,
    draftId?: string,
  ): Promise<ProductionDraft<K>> {
    const draft: ProductionDraft<K> = {
      id: draftId ?? this.nextId("draft"),
      kind,
      savedAt: new Date().toISOString(),
      input: clone(input),
    };
    const others = this.state.drafts.filter((d) => d.id !== draft.id);
    this.state.drafts = [draft as ProductionDraft, ...others];
    return clone(draft);
  }

  async postDraft<K extends ProductionKind>(kind: K, draftId: string): Promise<CreatedDocument> {
    const draft = this.state.drafts.find((d) => d.id === draftId && d.kind === kind);
    if (!draft) fail("form", "Draft not found");
    const created = this.post(kind, clone(draft!.input) as InputOf<K>);
    this.state.drafts = this.state.drafts.filter((d) => d.id !== draftId);
    return created;
  }

  async deleteDraft(kind: ProductionKind, draftId: string): Promise<void> {
    this.state.drafts = this.state.drafts.filter((d) => !(d.id === draftId && d.kind === kind));
  }

  async adjustJobCard(input: JobCardAdjustmentInput): Promise<void> {
    const card = this.state.jobCards.find((c) => c.id === input.jobCardId);
    if (!card) return fail("jobCardId", "Select a job card");
    this.requireDate(input.date);
    if (!isPositiveQty(input.qty)) fail("qty", "Adjustment quantity must be greater than 0");
    if (!input.reason.trim()) fail("reason", "A reason is required for every adjustment");
    const balance = this.jobCardBalance(card);
    if (compareQty(input.qty, balance) > 0) {
      fail("qty", `Adjustment cannot exceed the balance of ${formatQty(balance)}`);
    }
    card.adjustments.push({
      id: this.nextId("adj"),
      date: input.date,
      qty: input.qty,
      reason: input.reason.trim(),
    });
  }

  async getAvailableQty(query: StockQuery): Promise<number> {
    switch (query.kind) {
      case "yarn":
        return this.state.yarnStock.get(`${query.warehouseId}|${query.yarnId}`) ?? 0;
      case "fabric":
        return (
          this.state.fabricStock.get(`${query.warehouseId}|${query.itemId}|${query.yarnId}`) ?? 0
        );
      case "cuttingSource":
        return this.cuttingSource(query.jobOrderId, query.itemId, query.yarnId);
    }
  }

  async listDailyProductionLines(range: DateRange): Promise<DailyProductionLineRow[]> {
    const m = this.state.masters;
    return this.state.dailyProductions
      .filter((p) => isWithinRange(p.date, range.from, range.to))
      .flatMap((p) =>
        p.lines.map((line): DailyProductionLineRow => {
          const card = this.jobCard(line.jobCardId);
          const jo = this.jobOrder(card.jobOrderId);
          const item = m.items.find((i) => i.id === card.itemId);
          const unit = m.units.find((u) => u.id === p.unitId);
          return {
            lineId: line.id,
            productionId: p.id,
            receiveNo: p.number,
            date: p.date,
            jobCardId: card.id,
            jobChallanNo: card.number,
            jobOrderNo: jo.number,
            salesOrderNo: this.name(m.salesOrders, jo.salesOrderId),
            partyId: jo.orderPartyId,
            partyName: this.name(m.parties, jo.orderPartyId),
            itemId: card.itemId,
            itemCode: item?.code ?? "—",
            itemName: item?.name ?? "—",
            category: item?.category ?? "—",
            yarnId: card.yarnId,
            yarnName: this.name(m.yarns, card.yarnId),
            machineId: card.machineId,
            machineName: this.name(m.machines, card.machineId),
            unitId: p.unitId,
            unitName: unit?.name ?? "—",
            companyId: unit?.companyId ?? "",
            qty: line.qty,
            saleRate: line.saleRate,
            pickRate: line.pickRate,
            rate: line.rate,
            amount: lineAmount(line.qty, line.rate),
          };
        }),
      )
      .sort((a, b) => b.date.localeCompare(a.date) || b.receiveNo.localeCompare(a.receiveNo));
  }

  async traceJobOrder(jobOrderId: string): Promise<TraceStage[]> {
    const s = this.state;
    const jo = s.jobOrders.find((j) => j.id === jobOrderId);
    if (!jo) return [];
    const so = s.masters.salesOrders.find((o) => o.id === jo.salesOrderId);
    const cards = s.jobCards.filter((c) => c.jobOrderId === jo.id);
    const cardIds = new Set(cards.map((c) => c.id));
    const issues = s.yarnIssues.filter((i) => i.jobOrderId === jo.id);
    const issueIds = new Set(issues.map((i) => i.id));
    const outward = (process: OutwardProcess) => {
      const iss = s.outwardIssues.filter((i) => i.process === process && i.jobOrderId === jo.id);
      const ids = new Set(iss.map((i) => i.id));
      return [...iss, ...s.outwardReceipts.filter((r) => ids.has(r.issueId))];
    };
    const ref = (docs: { id: string; number: string; date: IsoDate }[]) =>
      docs
        .map(({ id, number, date }) => ({ id, number, date }))
        .sort((a, b) => a.date.localeCompare(b.date));
    const stages: TraceStage[] = [
      {
        stage: "Sales Order",
        documents: so ? [{ id: so.id, number: so.code, date: so.orderDate }] : [],
      },
      { stage: "Job Order", documents: ref([jo]) },
      { stage: "Job Card", documents: ref(cards) },
      { stage: "Yarn Issue", documents: ref(issues) },
      {
        stage: "Yarn Return",
        documents: ref(s.yarnReturns.filter((r) => issueIds.has(r.yarnIssueId))),
      },
      {
        stage: "Daily Production",
        documents: ref(
          s.dailyProductions.filter((p) => p.lines.some((l) => cardIds.has(l.jobCardId))),
        ),
      },
      {
        stage: "Job Receive",
        documents: ref(s.jobCardReceipts.filter((r) => cardIds.has(r.jobCardId))),
      },
      { stage: "Butta Cutting", documents: ref(outward("butta")) },
      { stage: "Mill Processing", documents: ref(outward("mill")) },
      { stage: "Cutting", documents: ref(s.cuttings.filter((c) => c.jobOrderId === jo.id)) },
      {
        stage: "Stock Conversion",
        documents: ref(s.conversions.filter((c) => c.stockOut.some((l) => l.jobOrderId === jo.id))),
      },
    ];
    return stages.filter((st) => st.documents.length > 0);
  }

  // -------------------------------------------------------------------------
  // Posting (validation + linked effects)
  // -------------------------------------------------------------------------

  private post<K extends ProductionKind>(kind: K, input: InputOf<K>): CreatedDocument {
    // Validate everything before touching state, so a rejected document changes nothing.
    const apply = this.prepare(kind, input);
    const id = this.nextId(kind);
    this.state.counters[kind] += 1;
    const number = `${DEMO_NUMBER_PREFIX[kind]}/${String(this.state.counters[kind]).padStart(4, "0")}`;
    apply({ id, number, createdAt: new Date().toISOString(), documentStatus: "POSTED" });
    return { id, number };
  }

  private prepare<K extends ProductionKind>(
    kind: K,
    raw: InputOf<K>,
  ): (base: { id: string; number: string; createdAt: string; documentStatus: "POSTED" }) => void {
    const s = this.state;
    const m = s.masters;
    switch (kind) {
      case "jobOrder": {
        const input = raw as InputOf<"jobOrder">;
        this.requireDate(input.date);
        this.requireRef("orderPartyId", input.orderPartyId, m.parties, "order party");
        this.requireRef("salesOrderId", input.salesOrderId, m.salesOrders, "order no.");
        this.requireRef("itemId", input.itemId, m.items, "item");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn item");
        this.requirePositive("qty", input.qty, "Quantity");
        this.requireNonNegative("rate", input.rate, "Rate");
        if (input.deliveryDate && !isIsoDate(input.deliveryDate)) {
          fail("deliveryDate", "Enter a valid delivery date");
        }
        const { date, remark, priority, deliveryDate, ...rest } = input;
        return (base) =>
          s.jobOrders.push({
            ...base,
            date,
            remark,
            ...rest,
            priority: priority ?? "normal",
            deliveryDate: deliveryDate ?? "",
            partyOrderNo: rest.partyOrderNo.trim(),
          });
      }
      case "yarnIssue": {
        const input = raw as InputOf<"yarnIssue">;
        this.requireDate(input.date);
        this.requireRef("jobOrderId", input.jobOrderId, s.jobOrders, "job order");
        this.requireRef("warehouseId", input.warehouseId, m.warehouses, "warehouse");
        this.requireRef("unitId", input.unitId, m.units, "unit");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn / item");
        this.requirePositive("qty", input.qty, "Issue quantity");
        this.requireNonNegative("rate", input.rate, "Rate");
        const key = `${input.warehouseId}|${input.yarnId}`;
        const available = s.yarnStock.get(key) ?? 0;
        if (compareQty(input.qty, available) > 0) {
          fail("qty", `Issue quantity exceeds demo available stock of ${formatQty(available)}`);
        }
        const { date, remark, ...rest } = input;
        return (base) => {
          s.yarnStock.set(key, subtractQty(available, input.qty));
          s.yarnIssues.push({ ...base, date, remark, ...rest });
        };
      }
      case "yarnReturn": {
        const input = raw as InputOf<"yarnReturn">;
        this.requireDate(input.date);
        const issue = s.yarnIssues.find((i) => i.id === input.yarnIssueId);
        if (!issue) return fail("yarnIssueId", "Select the original yarn issue");
        this.requirePositive("qty", input.qty, "Return quantity");
        const outstanding = this.yarnOutstanding(issue);
        if (compareQty(input.qty, outstanding) > 0) {
          fail("qty", `Return quantity cannot exceed the outstanding ${formatQty(outstanding)}`);
        }
        if (input.date < issue.date) fail("date", "Return date cannot be before the issue date");
        const key = `${issue.warehouseId}|${issue.yarnId}`;
        return (base) => {
          s.yarnStock.set(key, sumQty([s.yarnStock.get(key) ?? 0, input.qty]));
          s.yarnReturns.push({
            ...base,
            date: input.date,
            remark: input.remark,
            yarnIssueId: issue.id,
            qty: input.qty,
          });
        };
      }
      case "jobCard": {
        const input = raw as InputOf<"jobCard">;
        this.requireDate(input.date);
        this.requireRef("jobOrderId", input.jobOrderId, s.jobOrders, "job order");
        this.requireRef("partyId", input.partyId, m.parties, "party");
        if (!input.cardNo.trim()) fail("cardNo", "Card No. is required");
        this.requireRef("itemId", input.itemId, m.items, "item");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn");
        this.requireRef("machineId", input.machineId, m.machines, "machine / loom");
        this.requireRef("unitId", input.unitId, m.units, "unit");
        this.requirePositive("issuedQty", input.issuedQty, "Issued quantity");
        const { date, remark, ...rest } = input;
        return (base) =>
          s.jobCards.push({
            ...base,
            date,
            remark,
            ...rest,
            cardNo: rest.cardNo.trim(),
            adjustments: [],
          });
      }
      case "dailyProduction": {
        const input = raw as InputOf<"dailyProduction">;
        this.requireDate(input.date);
        this.requireRef("warehouseId", input.warehouseId, m.warehouses, "warehouse");
        this.requireRef("unitId", input.unitId, m.units, "unit");
        if (input.lines.length === 0) fail("lines", "Add at least one job card");
        const perCard = new Map<string, number>();
        input.lines.forEach((line, i) => {
          const card = s.jobCards.find((c) => c.id === line.jobCardId);
          if (!card) return fail(`lines.${i}.jobCardId`, `Line ${i + 1}: select a job card`);
          this.requirePositive(`lines.${i}.qty`, line.qty, `Line ${i + 1}: production quantity`);
          for (const [field, value] of [
            ["saleRate", line.saleRate],
            ["pickRate", line.pickRate],
            ["rate", line.rate],
          ] as const) {
            this.requireNonNegative(`lines.${i}.${field}`, value, `Line ${i + 1}: ${field}`);
          }
          for (const [field, value] of [
            ["yarnUsedKg", line.yarnUsedKg],
            ["downtimeMin", line.downtimeMin],
          ] as const) {
            if (value != null) {
              this.requireNonNegative(`lines.${i}.${field}`, value, `Line ${i + 1}: ${field}`);
            }
          }
          perCard.set(card.id, sumQty([perCard.get(card.id) ?? 0, line.qty]));
        });
        for (const [cardId, qty] of perCard) {
          const card = this.jobCard(cardId);
          const balance = this.jobCardBalance(card);
          if (compareQty(qty, balance) > 0) {
            const index = input.lines.findIndex((l) => l.jobCardId === cardId);
            fail(
              `lines.${index}.qty`,
              `${card.number}: production ${formatQty(qty)} exceeds the job card balance of ${formatQty(balance)}`,
            );
          }
        }
        return (base) =>
          s.dailyProductions.push({
            ...base,
            date: input.date,
            remark: input.remark,
            warehouseId: input.warehouseId,
            unitId: input.unitId,
            receiveType: "DAILY PRODUCTION",
            shift: input.shift ?? "",
            lines: input.lines.map((l) => ({
              ...l,
              yarnUsedKg: l.yarnUsedKg ?? null,
              downtimeMin: l.downtimeMin ?? null,
              downtimeReason: l.downtimeReason?.trim() ?? "",
              id: this.nextId("dpl"),
            })),
          });
      }
      case "jobCardReceipt": {
        const input = raw as InputOf<"jobCardReceipt">;
        this.requireDate(input.date);
        const card = s.jobCards.find((c) => c.id === input.jobCardId);
        if (!card) return fail("jobCardId", "Select the original job card / challan");
        this.requireRef("unitId", input.unitId, m.units, "unit");
        if (input.beamId) this.requireRef("beamId", input.beamId, m.beams, "beam");
        this.requirePositive("receiveQty", input.receiveQty, "Receive quantity");
        this.requireNonNegative("saleQty", input.saleQty, "Sale quantity");
        this.requireNonNegative("stockQty", input.stockQty, "Stock quantity");
        this.requireNonNegative("pickRate", input.pickRate, "Pick rate");
        if (!input.stockStatus) fail("stockStatus", "Select a stock status");
        const balance = this.jobCardBalance(card);
        if (compareQty(input.receiveQty, balance) > 0) {
          fail(
            "receiveQty",
            `Receive quantity cannot exceed the outstanding ${formatQty(balance)}`,
          );
        }
        const { date, remark, ...rest } = input;
        return (base) => s.jobCardReceipts.push({ ...base, date, remark, ...rest });
      }
      case "buttaIssue":
      case "millIssue": {
        const input = raw as InputOf<"buttaIssue">;
        const process = OUTWARD[kind as "buttaIssue"];
        this.requireDate(input.date);
        if (process === "butta")
          this.requireRef("warehouseId", input.warehouseId ?? "", m.warehouses, "warehouse");
        this.requireRef("partyId", input.partyId, m.parties, "mill / job work party");
        this.requireRef("jobOrderId", input.jobOrderId, s.jobOrders, "job order");
        this.requireRef("itemId", input.itemId, m.items, "item");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn");
        this.requirePositive("qty", input.qty, "Issue quantity");
        this.requireNonNegative("metres", input.metres, "Metres");
        const { date, remark, ...rest } = input;
        return (base) =>
          s.outwardIssues.push({
            ...base,
            date,
            remark,
            ...rest,
            warehouseId: process === "butta" ? rest.warehouseId : null,
            process,
          });
      }
      case "buttaReceipt":
      case "millReceipt": {
        const input = raw as InputOf<"buttaReceipt">;
        const process = OUTWARD[kind as "buttaReceipt"];
        this.requireDate(input.date);
        const issue = s.outwardIssues.find((i) => i.id === input.issueId && i.process === process);
        if (!issue) return fail("issueId", "Select the original issue");
        this.requireRef("warehouseId", input.warehouseId, m.warehouses, "warehouse");
        this.requirePositive("receiveQty", input.receiveQty, "Receive quantity");
        for (const [field, label] of [
          ["metres", "Metres"],
          ["saleQty", "Sale quantity"],
          ["stockQty", "Stock quantity"],
          ["rate", "Rate"],
        ] as const) {
          this.requireNonNegative(field, input[field], label);
        }
        if (!input.stockStatus) fail("stockStatus", "Select a stock status");
        const balance = this.outwardBalance(issue);
        if (compareQty(input.receiveQty, balance) > 0) {
          fail(
            "receiveQty",
            `Receive quantity cannot exceed the outstanding ${formatQty(balance)}`,
          );
        }
        const { date, remark, ...rest } = input;
        return (base) => s.outwardReceipts.push({ ...base, date, remark, ...rest, process });
      }
      case "fabricTransfer": {
        const input = raw as InputOf<"fabricTransfer">;
        this.requireDate(input.date);
        this.requireRef("fromWarehouseId", input.fromWarehouseId, m.warehouses, "from warehouse");
        this.requireRef("toWarehouseId", input.toWarehouseId, m.warehouses, "to warehouse");
        if (input.fromWarehouseId === input.toWarehouseId) {
          fail("toWarehouseId", "To Warehouse must be different from From Warehouse");
        }
        if (input.jobCardId) this.requireRef("jobCardId", input.jobCardId, s.jobCards, "job card");
        this.requireRef("itemId", input.itemId, m.items, "item");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn");
        this.requirePositive("qty", input.qty, "Transfer quantity");
        const fromKey = `${input.fromWarehouseId}|${input.itemId}|${input.yarnId}`;
        const toKey = `${input.toWarehouseId}|${input.itemId}|${input.yarnId}`;
        const available = s.fabricStock.get(fromKey) ?? 0;
        if (compareQty(input.qty, available) > 0) {
          fail("qty", `Transfer quantity exceeds demo available stock of ${formatQty(available)}`);
        }
        const { date, remark, ...rest } = input;
        return (base) => {
          // FINAL BACKEND MUST PERFORM BOTH MOVEMENTS ATOMICALLY.
          s.fabricStock.set(fromKey, subtractQty(available, input.qty));
          s.fabricStock.set(toKey, sumQty([s.fabricStock.get(toKey) ?? 0, input.qty]));
          s.fabricTransfers.push({ ...base, date, remark, ...rest });
        };
      }
      case "cutting": {
        const input = raw as InputOf<"cutting">;
        this.requireDate(input.date);
        this.requireRef("salesOrderId", input.salesOrderId, m.salesOrders, "sales order");
        this.requireRef("jobOrderId", input.jobOrderId, s.jobOrders, "job order");
        this.requireRef("itemId", input.itemId, m.items, "item");
        this.requireRef("yarnId", input.yarnId, m.yarns, "yarn");
        this.requireRef("gradeId", input.gradeId, m.grades, "grade");
        this.requirePositive("qty", input.qty, "Cutting quantity");
        const available = this.cuttingSource(input.jobOrderId, input.itemId, input.yarnId);
        if (compareQty(input.qty, available) > 0) {
          fail("qty", `Cutting quantity exceeds the demo available ${formatQty(available)}`);
        }
        const { date, remark, ...rest } = input;
        return (base) => s.cuttings.push({ ...base, date, remark, ...rest });
      }
      case "fabricConversion": {
        const input = raw as InputOf<"fabricConversion">;
        this.requireDate(input.date);
        if (!input.conversionType) fail("conversionType", "Select a type");
        this.requireRef("warehouseId", input.warehouseId, m.warehouses, "warehouse");
        if (input.stockOut.length === 0) fail("stockOut", "Add at least one stock out line");
        if (input.stockIn.length === 0) fail("stockIn", "Add at least one stock in line");
        input.stockOut.forEach((l, i) => {
          this.requireRef(
            `stockOut.${i}.jobOrderId`,
            l.jobOrderId,
            s.jobOrders,
            `stock out line ${i + 1} job order`,
          );
          this.requireRef(
            `stockOut.${i}.itemId`,
            l.itemId,
            m.items,
            `stock out line ${i + 1} item`,
          );
          this.requireRef(
            `stockOut.${i}.yarnId`,
            l.yarnId,
            m.yarns,
            `stock out line ${i + 1} yarn`,
          );
          this.requireRef(
            `stockOut.${i}.unitId`,
            l.unitId,
            m.units,
            `stock out line ${i + 1} unit`,
          );
          this.requirePositive(`stockOut.${i}.qty`, l.qty, `Stock out line ${i + 1}: quantity`);
        });
        input.stockIn.forEach((l, i) => {
          this.requireRef(`stockIn.${i}.itemId`, l.itemId, m.items, `stock in line ${i + 1} item`);
          this.requireRef(`stockIn.${i}.unitId`, l.unitId, m.units, `stock in line ${i + 1} unit`);
          this.requirePositive(`stockIn.${i}.qty`, l.qty, `Stock in line ${i + 1}: quantity`);
        });
        const out = sumQty(input.stockOut.map((l) => l.qty));
        const inn = sumQty(input.stockIn.map((l) => l.qty));
        if (input.quantityPreserving && compareQty(out, inn) !== 0) {
          fail(
            "stockIn",
            `Quantity preserving: stock in ${formatQty(inn)} must equal stock out ${formatQty(out)}`,
          );
        }
        const { date, remark, stockOut, stockIn, ...rest } = input;
        return (base) =>
          s.conversions.push({
            ...base,
            date,
            remark,
            ...rest,
            convertBy: rest.convertBy.trim(),
            productName: rest.productName.trim(),
            stockOut: stockOut.map((l) => ({ ...l, id: this.nextId("cvo") })),
            stockIn: stockIn.map((l) => ({ ...l, id: this.nextId("cvi") })),
          });
      }
    }
    return fail("form", `Unsupported document type ${kind}`);
  }

  // -------------------------------------------------------------------------
  // Derived quantities (PREVIEW — FINAL BACKEND MUST RECALCULATE)
  // -------------------------------------------------------------------------

  private yarnReturned(issue: YarnIssue): number {
    return sumQty(
      this.state.yarnReturns.filter((r) => r.yarnIssueId === issue.id).map((r) => r.qty),
    );
  }

  private yarnOutstanding(issue: YarnIssue): number {
    return subtractQty(issue.qty, this.yarnReturned(issue));
  }

  private jobCardReceived(card: JobCard): number {
    const production = this.state.dailyProductions.flatMap((p) =>
      p.lines.filter((l) => l.jobCardId === card.id).map((l) => l.qty),
    );
    const receipts = this.state.jobCardReceipts
      .filter((r) => r.jobCardId === card.id)
      .map((r) => r.receiveQty);
    return sumQty([...production, ...receipts]);
  }

  private jobCardBalance(card: JobCard): number {
    return subtractQty(
      card.issuedQty,
      this.jobCardReceived(card),
      sumQty(card.adjustments.map((a) => a.qty)),
    );
  }

  private outwardReceived(issue: OutwardIssue): number {
    return sumQty(
      this.state.outwardReceipts.filter((r) => r.issueId === issue.id).map((r) => r.receiveQty),
    );
  }

  private outwardBalance(issue: OutwardIssue): number {
    return subtractQty(issue.qty, this.outwardReceived(issue));
  }

  private cuttingSource(jobOrderId: string, itemId: string, yarnId: string): number {
    const received = this.state.jobCards
      .filter((c) => c.jobOrderId === jobOrderId && c.itemId === itemId && c.yarnId === yarnId)
      .map((c) => this.jobCardReceived(c));
    const cut = this.state.cuttings
      .filter((c) => c.jobOrderId === jobOrderId && c.itemId === itemId && c.yarnId === yarnId)
      .map((c) => c.qty);
    return subtractQty(sumQty(received), sumQty(cut));
  }

  private static status(balance: number): OperationalStatus {
    return compareQty(balance, 0) > 0 ? "Pending" : "Close";
  }

  // -------------------------------------------------------------------------
  // Row builders
  // -------------------------------------------------------------------------

  private rows<K extends ProductionKind>(kind: K): RowOf<K>[] {
    const s = this.state;
    const m = s.masters;
    const n = <T extends MasterOption>(list: T[], id: string | null) => this.name(list, id);
    const jobCardRow = (c: JobCard): JobCardRow => {
      const jo = this.jobOrder(c.jobOrderId);
      const received = this.jobCardReceived(c);
      const adjustment = sumQty(c.adjustments.map((a) => a.qty));
      const balance = subtractQty(c.issuedQty, received, adjustment);
      return {
        ...clone(c),
        jobOrderNo: jo.number,
        salesOrderNo: n(m.salesOrders, jo.salesOrderId),
        partyName: n(m.parties, c.partyId),
        itemName: n(m.items, c.itemId),
        yarnName: n(m.yarns, c.yarnId),
        machineName: n(m.machines, c.machineId),
        unitName: n(m.units, c.unitId),
        receivedQty: received,
        adjustmentQty: adjustment,
        balanceQty: balance,
        status: ProductionDemoService.status(balance),
      };
    };
    const outwardIssueRow = (i: OutwardIssue): OutwardIssueRow => {
      const received = this.outwardReceived(i);
      const balance = subtractQty(i.qty, received);
      return {
        ...clone(i),
        warehouseName: n(m.warehouses, i.warehouseId),
        partyName: n(m.parties, i.partyId),
        jobOrderNo: this.jobOrder(i.jobOrderId).number,
        itemName: n(m.items, i.itemId),
        yarnName: n(m.yarns, i.yarnId),
        receivedQty: received,
        balanceQty: balance,
        status: ProductionDemoService.status(balance),
      };
    };
    const outwardReceiptRows = (process: OutwardProcess) =>
      s.outwardReceipts
        .filter((r) => r.process === process)
        .map((r) => {
          const issue = s.outwardIssues.find((i) => i.id === r.issueId)!;
          return {
            ...clone(r),
            issueNo: issue.number,
            warehouseName: n(m.warehouses, r.warehouseId),
            partyName: n(m.parties, issue.partyId),
            jobOrderId: issue.jobOrderId,
            jobOrderNo: this.jobOrder(issue.jobOrderId).number,
            itemName: n(m.items, issue.itemId),
            yarnName: n(m.yarns, issue.yarnId),
            amount: lineAmount(r.receiveQty, r.rate),
          };
        });

    const byKind: { [P in ProductionKind]: () => RowOf<P>[] } = {
      jobOrder: () =>
        s.jobOrders.map((j) => {
          const cards = s.jobCards.filter((c) => c.jobOrderId === j.id);
          return {
            ...clone(j),
            partyName: n(m.parties, j.orderPartyId),
            salesOrderNo: n(m.salesOrders, j.salesOrderId),
            itemName: n(m.items, j.itemId),
            yarnName: n(m.yarns, j.yarnId),
            amount: lineAmount(j.qty, j.rate),
            cardIssuedQty: sumQty(cards.map((c) => c.issuedQty)),
            // Progress preview only — BUSINESS RULE PENDING CONFIRMATION (units of
            // job order qty vs job card qty are assumed to match).
            producedQty: sumQty(cards.map((c) => this.jobCardReceived(c))),
          };
        }),
      yarnIssue: () =>
        s.yarnIssues.map((i) => {
          const jo = this.jobOrder(i.jobOrderId);
          const returned = this.yarnReturned(i);
          return {
            ...clone(i),
            jobOrderNo: jo.number,
            partyName: n(m.parties, jo.orderPartyId),
            warehouseName: n(m.warehouses, i.warehouseId),
            unitName: n(m.units, i.unitId),
            yarnName: n(m.yarns, i.yarnId),
            amount: lineAmount(i.qty, i.rate),
            returnedQty: returned,
            outstandingQty: subtractQty(i.qty, returned),
          };
        }),
      yarnReturn: () =>
        s.yarnReturns.map((r) => {
          const issue = s.yarnIssues.find((i) => i.id === r.yarnIssueId)!;
          const jo = this.jobOrder(issue.jobOrderId);
          return {
            ...clone(r),
            issueNo: issue.number,
            jobOrderId: jo.id,
            jobOrderNo: jo.number,
            partyName: n(m.parties, jo.orderPartyId),
            productType: m.yarns.find((y) => y.id === issue.yarnId)?.productType ?? "—",
            yarnName: n(m.yarns, issue.yarnId),
            issueQty: issue.qty,
            amount: lineAmount(r.qty, issue.rate),
          };
        }),
      jobCard: () => s.jobCards.map(jobCardRow),
      dailyProduction: () =>
        s.dailyProductions.map((p) => ({
          ...clone(p),
          warehouseName: n(m.warehouses, p.warehouseId),
          unitName: n(m.units, p.unitId),
          lineCount: p.lines.length,
          totalQty: sumQty(p.lines.map((l) => l.qty)),
          totalAmount: sumAmount(p.lines.map((l) => lineAmount(l.qty, l.rate))),
        })),
      jobCardReceipt: () =>
        s.jobCardReceipts.map((r) => {
          const card = this.jobCard(r.jobCardId);
          const jo = this.jobOrder(card.jobOrderId);
          return {
            ...clone(r),
            jobChallanNo: card.number,
            jobOrderId: jo.id,
            jobOrderNo: jo.number,
            salesOrderNo: n(m.salesOrders, jo.salesOrderId),
            itemName: n(m.items, card.itemId),
            yarnName: n(m.yarns, card.yarnId),
            partyName: n(m.parties, card.partyId),
            cardNo: card.cardNo,
            unitName: n(m.units, r.unitId),
            machineName: n(m.machines, card.machineId),
            beamName: n(m.beams, r.beamId),
            // Demo preview only: formula pending confirmation.
            amount: lineAmount(r.receiveQty, r.pickRate),
          };
        }),
      buttaIssue: () => s.outwardIssues.filter((i) => i.process === "butta").map(outwardIssueRow),
      buttaReceipt: () => outwardReceiptRows("butta"),
      millIssue: () => s.outwardIssues.filter((i) => i.process === "mill").map(outwardIssueRow),
      millReceipt: () => outwardReceiptRows("mill"),
      fabricTransfer: () =>
        s.fabricTransfers.map((t) => ({
          ...clone(t),
          fromWarehouseName: n(m.warehouses, t.fromWarehouseId),
          toWarehouseName: n(m.warehouses, t.toWarehouseId),
          jobCardNo: t.jobCardId ? this.jobCard(t.jobCardId).number : "—",
          itemName: n(m.items, t.itemId),
          yarnName: n(m.yarns, t.yarnId),
        })),
      cutting: () =>
        s.cuttings.map((c) => ({
          ...clone(c),
          salesOrderNo: n(m.salesOrders, c.salesOrderId),
          jobOrderNo: this.jobOrder(c.jobOrderId).number,
          itemName: n(m.items, c.itemId),
          yarnName: n(m.yarns, c.yarnId),
          gradeName: n(m.grades, c.gradeId),
        })),
      fabricConversion: () =>
        s.conversions.map((c) => {
          const out = sumQty(c.stockOut.map((l) => l.qty));
          const inn = sumQty(c.stockIn.map((l) => l.qty));
          return {
            ...clone(c),
            warehouseName: n(m.warehouses, c.warehouseId),
            totalOutQty: out,
            totalInQty: inn,
            differenceQty: subtractQty(inn, out),
          };
        }),
    };
    return byKind[kind]();
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  private nextId(prefix: string): string {
    this.state.seq += 1;
    return `demo-${prefix}-${this.state.seq}`;
  }

  private name<T extends MasterOption>(list: T[], id: string | null): string {
    if (!id) return "—";
    return list.find((x) => x.id === id)?.name ?? "—";
  }

  private jobOrder(id: string): JobOrder {
    const jo = this.state.jobOrders.find((j) => j.id === id);
    if (!jo) throw new Error(`Demo job order ${id} missing`);
    return jo;
  }

  private jobCard(id: string): JobCard {
    const card = this.state.jobCards.find((c) => c.id === id);
    if (!card) throw new Error(`Demo job card ${id} missing`);
    return card;
  }

  private requireDate(date: string): void {
    if (!date || !isIsoDate(date)) fail("date", "Enter a valid date");
  }

  private requireRef(field: string, id: string, list: { id: string }[], label: string): void {
    if (!id || !list.some((x) => x.id === id)) fail(field, `Select ${label}`);
  }

  private requirePositive(field: string, value: number, label: string): void {
    if (!isPositiveQty(value)) fail(field, `${label} must be greater than 0`);
  }

  private requireNonNegative(field: string, value: number, label: string): void {
    if (!Number.isFinite(value) || value < 0) fail(field, `${label} cannot be negative`);
  }
}
