/**
 * Warping (beam) frontend contracts. NOT a backend schema.
 *
 * Rebuilt from the old Beam Store register (beam entry, set no., warp yarn, ends, length,
 * rack, status, loom allocation, QR label) on the current architecture. Each beam is ONE
 * record shared by the Warping screens and by Production (job card receipt "Beam No.").
 * BUSINESS RELATIONSHIP TO VALIDATE: how this register maps to Inventory beam stock items.
 */
import type { IsoDate } from "@/lib/erp/formatting";

/** Beam statuses carried over from the old Beam Store register. */
export const BEAM_STATUSES = ["IN_STORE", "LOADED_ON_LOOM", "SIZING", "DEPLETED"] as const;
export type BeamStatus = (typeof BEAM_STATUSES)[number];

export const BEAM_STATUS_LABEL: Record<BeamStatus, string> = {
  IN_STORE: "In Store",
  LOADED_ON_LOOM: "Loaded on Loom",
  SIZING: "In Sizing Bay",
  DEPLETED: "Depleted / Empty",
};

export type BeamMovementKind = "PRODUCED" | "LOADED" | "UNLOADED" | "LOCATION_STATUS";

export const BEAM_MOVEMENT_LABEL: Record<BeamMovementKind, string> = {
  PRODUCED: "Beam production",
  LOADED: "Beam loading",
  UNLOADED: "Beam unload",
  LOCATION_STATUS: "Location / status update",
};

/** One status / location change of a beam (history; the latest one is current state). */
export type BeamMovement = {
  id: string;
  /** Demo number (e.g. BLD/0001). FINAL NUMBERING WILL BE GENERATED BY BACKEND. */
  number: string;
  beamId: string;
  kind: BeamMovementKind;
  date: IsoDate;
  fromStatus: BeamStatus | null;
  toStatus: BeamStatus;
  fromLoomId: string | null;
  toLoomId: string | null;
  fromRack: string;
  toRack: string;
  remark: string;
  createdAt: string;
};

export type BeamInput = {
  date: IsoDate;
  beamNo: string;
  setNo: string;
  beamType: string;
  warpYarnId: string;
  /** Count / denier as written on the beam card (free text in the old register). */
  countDenier: string;
  totalEnds: number;
  lengthMetre: number;
  rack: string;
  remark: string;
};

export type Beam = BeamInput & {
  id: string;
  /** Demo production number (BPR/…). */
  number: string;
  status: BeamStatus;
  loomId: string | null;
  /** Payload encoded in the QR label. */
  qrCode: string;
  createdAt: string;
};

export type BeamRow = Beam & {
  warpYarnName: string;
  loomName: string;
  /** Date of the latest movement. */
  lastMovedOn: IsoDate;
};

export type BeamMovementRow = BeamMovement & {
  beamNo: string;
  setNo: string;
  beamType: string;
  fromLoomName: string;
  toLoomName: string;
};

export type LoadBeamInput = { beamId: string; loomId: string; date: IsoDate; remark: string };
export type UnloadBeamInput = {
  beamId: string;
  date: IsoDate;
  toStatus: Exclude<BeamStatus, "LOADED_ON_LOOM">;
  rack: string;
  remark: string;
};
export type MoveBeamInput = {
  beamId: string;
  date: IsoDate;
  toStatus: Exclude<BeamStatus, "LOADED_ON_LOOM">;
  rack: string;
  remark: string;
};

export class WarpingValidationError extends Error {
  constructor(
    public readonly field: string,
    message: string,
  ) {
    super(message);
    this.name = "WarpingValidationError";
  }
}

export class WarpingUnavailableError extends Error {
  constructor() {
    super("Warping is not connected to the database yet; it runs in frontend prototype mode only.");
    this.name = "WarpingUnavailableError";
  }
}

/** The only thing the Warping screens talk to. Supabase implementation comes later. */
export interface WarpingService {
  readonly mode: "demo" | "unavailable";
  listBeams(): Promise<BeamRow[]>;
  listMovements(kind?: BeamMovementKind): Promise<BeamMovementRow[]>;
  produceBeam(input: BeamInput): Promise<Beam>;
  loadBeam(input: LoadBeamInput): Promise<BeamMovement>;
  unloadBeam(input: UnloadBeamInput): Promise<BeamMovement>;
  moveBeam(input: MoveBeamInput): Promise<BeamMovement>;
}
