/**
 * WarpingDemoService — FRONTEND PROTOTYPE ADAPTER for the beam lifecycle and the yarn
 * issued for beam production. In memory only (no Supabase, no localStorage); a reload
 * restores the fixtures. The final backend MUST re-implement the status / loom
 * transitions and yarn quantities atomically, including the yarn stock effect (not
 * simulated here), and decide the relationship with Inventory beam stock
 * (BUSINESS RELATIONSHIP TO VALIDATE). FINAL NUMBERING WILL BE GENERATED BY BACKEND.
 */
import { addDays, isIsoDate, todayIso } from "@/lib/erp/formatting";
import { compareQty, isPositiveQty, subtractQty, sumQty } from "@/lib/erp/numbers";
import { formatWeight } from "@/lib/erp/formatting";
import { DEMO_MASTERS } from "@/features/production/demo/production-demo-data";
import { DEMO_WARPING_SEEDS } from "@/features/production/warping/warping-demo-data";
import {
  WarpingValidationError,
  type Beam,
  type BeamInput,
  type BeamIssueInput,
  type BeamMovement,
  type BeamMovementKind,
  type BeamMovementRow,
  type BeamProductionLoadingInput,
  type BeamReceiveInput,
  type BeamRow,
  type BeamStatus,
  type EmptyBeamInwardInput,
  type LoadBeamInput,
  type MaterialIssue,
  type MaterialIssueInput,
  type MaterialIssueRow,
  type MaterialReturn,
  type MaterialReturnInput,
  type MaterialReturnRow,
  type MoveBeamInput,
  type UnloadBeamInput,
  type WarpDetails,
  type WarpingService,
  type YarnIssueUpdate,
  type YarnIssueUpdateInput,
  type YarnIssueUpdateRow,
} from "@/features/production/warping/warping-types";

type Counter = BeamMovementKind | "MATERIAL_ISSUE" | "MATERIAL_RETURN" | "YARN_UPDATE";

const PREFIX: Record<Counter, string> = {
  EMPTY_INWARD: "EBI",
  ISSUED_FOR_WARPING: "BIS",
  PRODUCED: "BPR",
  RECEIVED: "BRC",
  PRODUCED_LOADED: "BPL",
  LOADED: "BLD",
  UNLOADED: "BUL",
  LOCATION_STATUS: "BMV",
  MATERIAL_ISSUE: "BMI",
  MATERIAL_RETURN: "BMR",
  YARN_UPDATE: "TFO",
};

const fail = (field: string, message: string): never => {
  throw new WarpingValidationError(field, message);
};

type Move = {
  kind: BeamMovementKind;
  date: string;
  toStatus: BeamStatus;
  toLoomId?: string | null;
  rack?: string;
  partyId?: string;
  challanNo?: string;
  remark: string;
};

export class WarpingDemoService implements WarpingService {
  readonly mode = "demo" as const;
  private beams: Beam[] = [];
  private movements: BeamMovement[] = [];
  private materialIssues: MaterialIssue[] = [];
  private materialReturns: MaterialReturn[] = [];
  private yarnUpdates: YarnIssueUpdate[] = [];
  private counters = Object.fromEntries(
    (Object.keys(PREFIX) as Counter[]).map((k) => [k, 100]),
  ) as Record<Counter, number>;
  private seq = 0;
  private readonly looms = DEMO_MASTERS.machines;
  private readonly yarns = DEMO_MASTERS.yarns;
  private readonly parties = DEMO_MASTERS.parties;

  constructor(options: { seed?: boolean } = {}) {
    if (options.seed !== false) this.applySeeds();
  }

  // ---------------------------------------------------------------- queries

  async listBeams(): Promise<BeamRow[]> {
    return this.beams
      .map((b): BeamRow => {
        const last = this.movements.filter((m) => m.beamId === b.id).at(-1);
        return {
          ...structuredClone(b),
          setNo: b.warp?.setNo ?? "",
          warpYarnName: b.warp ? this.yarnName(b.warp.warpYarnId) : "",
          countDenier: b.warp?.countDenier ?? "",
          totalEnds: b.warp?.totalEnds ?? null,
          lengthMetre: b.warp?.lengthMetre ?? null,
          loomName: this.loomName(b.loomId),
          partyName: this.partyName(b.partyId),
          lastMovedOn: last?.date ?? b.date,
        };
      })
      .sort((a, b) => a.beamNo.localeCompare(b.beamNo));
  }

  async listMovements(kind?: BeamMovementKind): Promise<BeamMovementRow[]> {
    return this.movements
      .filter((m) => !kind || m.kind === kind)
      .map((m): BeamMovementRow => {
        const beam = this.beam(m.beamId);
        return {
          ...structuredClone(m),
          beamNo: beam.beamNo,
          // Set no. of the warp at the time is the beam's current set unless it was emptied later.
          setNo: beam.warp?.setNo ?? "",
          beamType: beam.beamType,
          fromLoomName: this.loomName(m.fromLoomId),
          toLoomName: this.loomName(m.toLoomId),
          partyName: this.partyName(m.partyId),
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
  }

  async listMaterialIssues(): Promise<MaterialIssueRow[]> {
    return this.materialIssues
      .map((i) => this.issueRow(i))
      .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
  }

  async listMaterialReturns(): Promise<MaterialReturnRow[]> {
    return this.materialReturns
      .map((r): MaterialReturnRow => {
        const issue = this.materialIssue(r.materialIssueId);
        return {
          ...structuredClone(r),
          issueNo: issue.number,
          beamNo: this.beam(issue.beamId).beamNo,
          yarnName: this.yarnName(issue.yarnId),
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
  }

  async listYarnIssueUpdates(): Promise<YarnIssueUpdateRow[]> {
    return this.yarnUpdates
      .map((u): YarnIssueUpdateRow => {
        const issue = this.materialIssue(u.materialIssueId);
        return {
          ...structuredClone(u),
          issueNo: issue.number,
          beamNo: this.beam(issue.beamId).beamNo,
          yarnName: this.yarnName(issue.yarnId),
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
  }

  // ---------------------------------------------------------------- beam lifecycle

  /** Empty Beam Inward: a new empty beam, or an at-warping beam returned unwarped. */
  async inwardEmptyBeam(input: EmptyBeamInwardInput): Promise<BeamMovement> {
    this.requireDate(input.date);
    this.optionalParty(input.partyId);
    const existing = this.findByNo(input.beamNo);
    if (existing) {
      if (existing.status !== "AT_WARPING") {
        fail(
          "beamNo",
          `${existing.beamNo} is already registered (${existing.status.replace(/_/g, " ").toLowerCase()})`,
        );
      }
      return clone(
        this.move(existing, {
          kind: "EMPTY_INWARD",
          date: input.date,
          toStatus: "EMPTY",
          rack: input.rack,
          partyId: input.partyId,
          challanNo: input.challanNo,
          remark: input.remark,
        }),
      );
    }
    const beam = this.newBeam(input.beamNo, input.beamType, input.date, input.remark);
    return clone(
      this.move(beam, {
        kind: "EMPTY_INWARD",
        date: input.date,
        toStatus: "EMPTY",
        rack: input.rack,
        partyId: input.partyId,
        challanNo: input.challanNo,
        remark: input.remark,
      }),
    );
  }

  /** Beam Issue Entry (Empty Beam): an empty beam goes for warping (in-house or party). */
  async issueBeam(input: BeamIssueInput): Promise<BeamMovement> {
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "EMPTY") fail("beamId", `${beam.beamNo} is not an empty beam in store`);
    this.optionalParty(input.partyId);
    return clone(
      this.move(beam, {
        kind: "ISSUED_FOR_WARPING",
        date: input.date,
        toStatus: "AT_WARPING",
        partyId: input.partyId,
        remark: input.remark,
      }),
    );
  }

  async produceBeam(input: BeamInput): Promise<BeamMovement> {
    return clone(this.warp("PRODUCED", input, "", "", null));
  }

  async receiveBeam(input: BeamReceiveInput): Promise<BeamMovement> {
    if (!input.partyId) fail("partyId", "Select the party the beam is received from");
    return clone(this.warp("RECEIVED", input, input.partyId, input.challanNo, null));
  }

  async produceAndLoadBeam(input: BeamProductionLoadingInput): Promise<BeamMovement> {
    this.requireLoom(input.loomId);
    return clone(this.warp("PRODUCED_LOADED", input, "", "", input.loomId));
  }

  async loadBeam(input: LoadBeamInput): Promise<BeamMovement> {
    return clone(this.load(input));
  }

  async unloadBeam(input: UnloadBeamInput): Promise<BeamMovement> {
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "LOADED_ON_LOOM") fail("beamId", `${beam.beamNo} is not loaded on a loom`);
    return clone(
      this.move(beam, {
        kind: "UNLOADED",
        date: input.date,
        toStatus: input.toStatus,
        rack: input.rack,
        remark: input.remark,
      }),
    );
  }

  async moveBeam(input: MoveBeamInput): Promise<BeamMovement> {
    const beam = this.requireBeam(input.beamId);
    if (beam.status === "LOADED_ON_LOOM") {
      fail("beamId", `${beam.beamNo} is on a loom — use Beam Unload Entry first`);
    }
    if (beam.status === "AT_WARPING") {
      fail("beamId", `${beam.beamNo} is at warping — record Beam Production / Receive first`);
    }
    if (beam.status === "EMPTY" && input.toStatus !== "EMPTY") {
      fail("toStatus", "An empty beam can only be moved between racks");
    }
    return clone(
      this.move(beam, {
        kind: "LOCATION_STATUS",
        date: input.date,
        toStatus: input.toStatus,
        rack: input.rack,
        remark: input.remark,
      }),
    );
  }

  // ---------------------------------------------------------------- yarn for beams

  async issueMaterial(input: MaterialIssueInput): Promise<MaterialIssue> {
    this.requireDate(input.date);
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "AT_WARPING") {
      fail("beamId", `${beam.beamNo} is not at warping — issue the empty beam first`);
    }
    if (!this.yarns.some((y) => y.id === input.yarnId)) fail("yarnId", "Select the yarn");
    if (!Number.isFinite(input.qtyKg) || !isPositiveQty(input.qtyKg)) {
      fail("qtyKg", "Issue quantity must be above zero");
    }
    const issue: MaterialIssue = {
      ...structuredClone(input),
      remark: input.remark.trim(),
      id: this.nextId("bmi"),
      number: this.nextNumber("MATERIAL_ISSUE"),
      createdAt: new Date().toISOString(),
    };
    this.materialIssues.push(issue);
    return clone(issue);
  }

  async returnMaterial(input: MaterialReturnInput): Promise<MaterialReturn> {
    this.requireDate(input.date);
    const issue = this.materialIssues.find((i) => i.id === input.materialIssueId);
    if (!issue) return fail("materialIssueId", "Select the original material issue");
    if (input.date < issue.date) fail("date", "Return date cannot be before the issue date");
    if (!Number.isFinite(input.qtyKg) || !isPositiveQty(input.qtyKg)) {
      fail("qtyKg", "Return quantity must be above zero");
    }
    const outstanding = this.issueRow(issue).netIssuedKg;
    if (compareQty(input.qtyKg, outstanding) > 0) {
      fail("qtyKg", `Only ${formatWeight(outstanding)} kg is outstanding on ${issue.number}`);
    }
    const ret: MaterialReturn = {
      ...structuredClone(input),
      remark: input.remark.trim(),
      id: this.nextId("bmr"),
      number: this.nextNumber("MATERIAL_RETURN"),
      createdAt: new Date().toISOString(),
    };
    this.materialReturns.push(ret);
    return clone(ret);
  }

  async updateYarnIssue(input: YarnIssueUpdateInput): Promise<YarnIssueUpdate> {
    this.requireDate(input.date);
    const issue = this.materialIssues.find((i) => i.id === input.materialIssueId);
    if (!issue) return fail("materialIssueId", "Select the material issue to update");
    if (!Number.isFinite(input.qtyChangeKg) || compareQty(input.qtyChangeKg, 0) === 0) {
      fail("qtyChangeKg", "Enter the change (+ more issued, − less issued)");
    }
    if (!input.reason.trim()) fail("reason", "A reason is required");
    const net = this.issueRow(issue).netIssuedKg;
    if (compareQty(sumQty([net, input.qtyChangeKg]), 0) < 0) {
      fail("qtyChangeKg", `Net issued cannot go below zero (currently ${formatWeight(net)} kg)`);
    }
    const update: YarnIssueUpdate = {
      ...structuredClone(input),
      reason: input.reason.trim(),
      id: this.nextId("tfo"),
      number: this.nextNumber("YARN_UPDATE"),
      createdAt: new Date().toISOString(),
    };
    this.yarnUpdates.push(update);
    return clone(update);
  }

  // ---------------------------------------------------------------- internals

  private applySeeds(): void {
    const today = todayIso();
    for (const s of DEMO_WARPING_SEEDS) {
      const date = addDays(today, -s.daysAgo);
      switch (s.op) {
        case "inward": {
          const beam = this.newBeam(s.beamNo, s.beamType, date, "", s.beam);
          this.move(beam, {
            kind: "EMPTY_INWARD",
            date,
            toStatus: "EMPTY",
            rack: s.rack,
            remark: "",
          });
          break;
        }
        case "issue":
          this.move(this.beam(s.beam), {
            kind: "ISSUED_FOR_WARPING",
            date,
            toStatus: "AT_WARPING",
            partyId: s.partyId,
            remark: "",
          });
          break;
        case "material":
          void this.issueMaterial({
            date,
            beamId: s.beam,
            yarnId: s.yarnId,
            qtyKg: s.qtyKg,
            remark: "",
          });
          break;
        case "return": {
          const issue = this.materialIssues[s.materialIndex];
          if (issue)
            void this.returnMaterial({
              date,
              materialIssueId: issue.id,
              qtyKg: s.qtyKg,
              remark: "",
            });
          break;
        }
        case "produce":
        case "receive": {
          const beam = this.beam(s.beam);
          const input: BeamInput = {
            ...s.warp,
            date,
            beamNo: beam.beamNo,
            beamType: beam.beamType,
            rack: s.rack,
            remark: "",
          };
          if (s.op === "produce") this.warp("PRODUCED", input, "", "", null);
          else this.warp("RECEIVED", input, s.partyId, s.challanNo, null);
          break;
        }
        case "load":
          this.load({ beamId: s.beam, loomId: s.loomId, date, remark: "" });
          break;
      }
    }
  }

  /**
   * Warp a beam (production / receive / production loading). An existing EMPTY or
   * AT_WARPING beam with that number is reused; an unknown number creates a new beam.
   */
  private warp(
    kind: "PRODUCED" | "RECEIVED" | "PRODUCED_LOADED",
    input: BeamInput,
    partyId: string,
    challanNo: string,
    loomId: string | null,
  ): BeamMovement {
    this.requireDate(input.date);
    const warp = this.validWarp(input);
    const existing = this.findByNo(input.beamNo);
    if (existing && existing.status !== "EMPTY" && existing.status !== "AT_WARPING") {
      fail(
        "beamNo",
        `${existing.beamNo} already carries a warp (${existing.status.replace(/_/g, " ").toLowerCase()})`,
      );
    }
    if (
      existing &&
      kind === "RECEIVED" &&
      existing.status === "AT_WARPING" &&
      existing.partyId &&
      existing.partyId !== partyId
    ) {
      fail("partyId", `${existing.beamNo} was issued to ${this.partyName(existing.partyId)}`);
    }
    if (!existing && !input.beamType.trim()) fail("beamType", "Select a beam type");
    const beam = existing ?? this.newBeam(input.beamNo, input.beamType, input.date, input.remark);
    if (existing && input.beamType.trim()) beam.beamType = input.beamType.trim();
    const movement = this.move(beam, {
      kind,
      date: input.date,
      toStatus: loomId ? "LOADED_ON_LOOM" : "IN_STORE",
      toLoomId: loomId,
      rack: loomId ? "" : input.rack,
      partyId,
      challanNo,
      remark: input.remark,
    });
    beam.warp = warp;
    beam.warpedOn = input.date;
    beam.qrCode = `SCKT-BEAM|${beam.beamNo}|${warp.setNo}`;
    return movement;
  }

  private validWarp(input: WarpDetails): WarpDetails {
    if (!input.setNo.trim()) fail("setNo", "Set No. is required");
    if (!this.yarns.some((y) => y.id === input.warpYarnId))
      fail("warpYarnId", "Select the warp yarn");
    if (!Number.isInteger(input.totalEnds) || input.totalEnds <= 0) {
      fail("totalEnds", "Total ends must be a whole number above zero");
    }
    if (!Number.isFinite(input.lengthMetre) || !isPositiveQty(input.lengthMetre)) {
      fail("lengthMetre", "Length must be above zero");
    }
    return {
      setNo: input.setNo.trim(),
      warpYarnId: input.warpYarnId,
      countDenier: input.countDenier.trim(),
      totalEnds: input.totalEnds,
      lengthMetre: input.lengthMetre,
    };
  }

  private load(input: LoadBeamInput): BeamMovement {
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "IN_STORE") {
      fail(
        "beamId",
        `${beam.beamNo} is ${beam.status === "LOADED_ON_LOOM" ? "already on a loom" : "not a warped beam in store"}`,
      );
    }
    this.requireLoom(input.loomId);
    // BUSINESS RULE PENDING CONFIRMATION: how many beams one loom may carry (ground +
    // border…) is not enforced.
    return this.move(beam, {
      kind: "LOADED",
      date: input.date,
      toStatus: "LOADED_ON_LOOM",
      toLoomId: input.loomId,
      rack: "",
      remark: input.remark,
    });
  }

  private newBeam(
    beamNo: string,
    beamType: string,
    date: string,
    remark: string,
    id?: string,
  ): Beam {
    this.requireDate(date);
    const no = beamNo.trim();
    if (!no) fail("beamNo", "Beam No. is required");
    if (this.findByNo(no)) fail("beamNo", `Beam ${no} already exists`);
    if (!beamType.trim()) fail("beamType", "Select a beam type");
    const beam: Beam = {
      id: id ?? this.nextId("beam"),
      number: "",
      beamNo: no,
      beamType: beamType.trim(),
      date,
      status: "EMPTY",
      loomId: null,
      rack: "",
      partyId: "",
      warp: null,
      warpedOn: null,
      qrCode: `SCKT-BEAM|${no}`,
      remark: remark.trim(),
      createdAt: new Date().toISOString(),
    };
    this.beams.push(beam);
    return beam;
  }

  private move(beam: Beam, m: Move): BeamMovement {
    this.requireDate(m.date);
    const last = this.movements.filter((x) => x.beamId === beam.id).at(-1);
    if (last && m.date < last.date)
      fail("date", `Date cannot be before the beam's last movement (${last.date})`);
    const movement: BeamMovement = {
      id: this.nextId("mv"),
      number: this.nextNumber(m.kind),
      beamId: beam.id,
      kind: m.kind,
      date: m.date,
      fromStatus: last ? beam.status : null,
      toStatus: m.toStatus,
      fromLoomId: beam.loomId,
      toLoomId: m.toLoomId ?? null,
      fromRack: beam.rack,
      toRack: (m.rack ?? "").trim(),
      partyId: m.partyId ?? "",
      challanNo: (m.challanNo ?? "").trim(),
      remark: m.remark.trim(),
      createdAt: new Date().toISOString(),
    };
    if (!beam.number) beam.number = movement.number;
    beam.status = m.toStatus;
    beam.loomId = m.toLoomId ?? null;
    beam.rack = movement.toRack;
    beam.partyId = m.toStatus === "AT_WARPING" ? movement.partyId : "";
    if (m.toStatus === "EMPTY") {
      beam.warp = null;
      beam.warpedOn = null;
      beam.qrCode = `SCKT-BEAM|${beam.beamNo}`;
    }
    this.movements.push(movement);
    return movement;
  }

  private issueRow(issue: MaterialIssue): MaterialIssueRow {
    const returned = sumQty(
      this.materialReturns.filter((r) => r.materialIssueId === issue.id).map((r) => r.qtyKg),
    );
    const adjustment = sumQty(
      this.yarnUpdates.filter((u) => u.materialIssueId === issue.id).map((u) => u.qtyChangeKg),
    );
    return {
      ...structuredClone(issue),
      beamNo: this.beam(issue.beamId).beamNo,
      yarnName: this.yarnName(issue.yarnId),
      returnedKg: returned,
      adjustmentKg: adjustment,
      netIssuedKg: subtractQty(sumQty([issue.qtyKg, adjustment]), returned),
    };
  }

  private findByNo(beamNo: string): Beam | undefined {
    const no = beamNo.trim().toLowerCase();
    return this.beams.find((b) => b.beamNo.toLowerCase() === no);
  }

  private requireBeam(id: string): Beam {
    const beam = this.beams.find((b) => b.id === id);
    if (!beam) return fail("beamId", "Select a beam");
    return beam;
  }

  private requireLoom(id: string): void {
    if (!this.looms.some((l) => l.id === id)) fail("loomId", "Select a loom");
  }

  private requireDate(date: string): void {
    if (!isIsoDate(date)) fail("date", "Enter a valid date");
  }

  private optionalParty(id: string): void {
    if (id && !this.parties.some((p) => p.id === id && p.kind === "job_work")) {
      fail("partyId", "Select a job work party");
    }
  }

  private beam(id: string): Beam {
    const beam = this.beams.find((b) => b.id === id);
    if (!beam) throw new Error(`Unknown beam ${id}`);
    return beam;
  }

  private materialIssue(id: string): MaterialIssue {
    const issue = this.materialIssues.find((i) => i.id === id);
    if (!issue) throw new Error(`Unknown material issue ${id}`);
    return issue;
  }

  private loomName(id: string | null): string {
    return id ? (this.looms.find((l) => l.id === id)?.name ?? "—") : "";
  }

  private yarnName(id: string): string {
    return this.yarns.find((y) => y.id === id)?.name ?? "—";
  }

  private partyName(id: string): string {
    return id ? (this.parties.find((p) => p.id === id)?.name ?? "—") : "In-house";
  }

  private nextNumber(kind: Counter): string {
    this.counters[kind] += 1;
    return `${PREFIX[kind]}/${String(this.counters[kind]).padStart(4, "0")}`;
  }

  private nextId(prefix: string): string {
    this.seq += 1;
    return `${prefix}-${Date.now().toString(36)}-${this.seq}`;
  }
}

function clone<T>(value: T): T {
  return structuredClone(value);
}
