/**
 * WarpingDemoService — FRONTEND PROTOTYPE ADAPTER for the beam register.
 * In memory only (no Supabase, no localStorage); a reload restores the fixtures.
 * The final backend MUST re-implement the status / loom transitions atomically and
 * decide the relationship with Inventory beam stock (BUSINESS RELATIONSHIP TO VALIDATE).
 * FINAL NUMBERING WILL BE GENERATED BY BACKEND.
 */
import { isIsoDate } from "@/lib/erp/formatting";
import { isPositiveQty } from "@/lib/erp/numbers";
import { DEMO_MASTERS } from "@/features/production/demo/production-demo-data";
import { DEMO_BEAM_SEEDS } from "@/features/production/warping/warping-demo-data";
import {
  WarpingValidationError,
  type Beam,
  type BeamInput,
  type BeamMovement,
  type BeamMovementKind,
  type BeamMovementRow,
  type BeamRow,
  type BeamStatus,
  type LoadBeamInput,
  type MoveBeamInput,
  type UnloadBeamInput,
  type WarpingService,
} from "@/features/production/warping/warping-types";
import { addDays, todayIso } from "@/lib/erp/formatting";

const PREFIX: Record<BeamMovementKind, string> = {
  PRODUCED: "BPR",
  LOADED: "BLD",
  UNLOADED: "BUL",
  LOCATION_STATUS: "BMV",
};

const fail = (field: string, message: string): never => {
  throw new WarpingValidationError(field, message);
};

export class WarpingDemoService implements WarpingService {
  readonly mode = "demo" as const;
  private beams: Beam[] = [];
  private movements: BeamMovement[] = [];
  private counters: Record<BeamMovementKind, number> = {
    PRODUCED: 4100,
    LOADED: 610,
    UNLOADED: 540,
    LOCATION_STATUS: 90,
  };
  private seq = 0;
  private readonly looms = DEMO_MASTERS.machines;
  private readonly yarns = DEMO_MASTERS.yarns;

  constructor(options: { seed?: boolean } = {}) {
    if (options.seed === false) return;
    for (const seed of DEMO_BEAM_SEEDS) {
      this.createBeam(seed.input, seed.id);
      if (seed.loadOn) {
        this.load({
          beamId: seed.id,
          loomId: seed.loadOn.loomId,
          date: addDays(todayIso(), -seed.loadOn.daysAgo),
          remark: "",
        });
      }
    }
  }

  async listBeams(): Promise<BeamRow[]> {
    return this.beams
      .map((b): BeamRow => {
        const last = this.movements.filter((m) => m.beamId === b.id).at(-1);
        return {
          ...structuredClone(b),
          warpYarnName: this.yarns.find((y) => y.id === b.warpYarnId)?.name ?? "—",
          loomName: this.loomName(b.loomId),
          lastMovedOn: last?.date ?? b.date,
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date) || b.beamNo.localeCompare(a.beamNo));
  }

  async listMovements(kind?: BeamMovementKind): Promise<BeamMovementRow[]> {
    return this.movements
      .filter((m) => !kind || m.kind === kind)
      .map((m): BeamMovementRow => {
        const beam = this.beam(m.beamId);
        return {
          ...structuredClone(m),
          beamNo: beam.beamNo,
          setNo: beam.setNo,
          beamType: beam.beamType,
          fromLoomName: this.loomName(m.fromLoomId),
          toLoomName: this.loomName(m.toLoomId),
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
  }

  async produceBeam(input: BeamInput): Promise<Beam> {
    return structuredClone(this.createBeam(input));
  }

  async loadBeam(input: LoadBeamInput): Promise<BeamMovement> {
    return structuredClone(this.load(input));
  }

  async unloadBeam(input: UnloadBeamInput): Promise<BeamMovement> {
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "LOADED_ON_LOOM") fail("beamId", `${beam.beamNo} is not loaded on a loom`);
    return structuredClone(
      this.move(beam, "UNLOADED", input.date, input.toStatus, null, input.rack, input.remark),
    );
  }

  async moveBeam(input: MoveBeamInput): Promise<BeamMovement> {
    const beam = this.requireBeam(input.beamId);
    if (beam.status === "LOADED_ON_LOOM") {
      fail("beamId", `${beam.beamNo} is on a loom — use Beam Unload Entry first`);
    }
    return structuredClone(
      this.move(
        beam,
        "LOCATION_STATUS",
        input.date,
        input.toStatus,
        null,
        input.rack,
        input.remark,
      ),
    );
  }

  // -------------------------------------------------------------------------

  private createBeam(input: BeamInput, id?: string): Beam {
    if (!isIsoDate(input.date)) fail("date", "Enter a valid date");
    const beamNo = input.beamNo.trim();
    if (!beamNo) fail("beamNo", "Beam No. is required");
    if (this.beams.some((b) => b.beamNo.toLowerCase() === beamNo.toLowerCase())) {
      fail("beamNo", `Beam ${beamNo} already exists`);
    }
    if (!input.setNo.trim()) fail("setNo", "Set No. is required");
    if (!input.beamType.trim()) fail("beamType", "Select a beam type");
    if (!this.yarns.some((y) => y.id === input.warpYarnId))
      fail("warpYarnId", "Select the warp yarn");
    if (!Number.isInteger(input.totalEnds) || input.totalEnds <= 0) {
      fail("totalEnds", "Total ends must be a whole number above zero");
    }
    if (!Number.isFinite(input.lengthMetre) || !isPositiveQty(input.lengthMetre)) {
      fail("lengthMetre", "Length must be above zero");
    }
    const beam: Beam = {
      ...structuredClone(input),
      beamNo,
      setNo: input.setNo.trim(),
      rack: input.rack.trim(),
      id: id ?? this.nextId("beam"),
      number: this.nextNumber("PRODUCED"),
      status: "IN_STORE",
      loomId: null,
      qrCode: `SCKT-BEAM|${beamNo}|${input.setNo.trim()}`,
      createdAt: new Date().toISOString(),
    };
    this.beams.push(beam);
    this.movements.push({
      id: this.nextId("mv"),
      number: beam.number,
      beamId: beam.id,
      kind: "PRODUCED",
      date: input.date,
      fromStatus: null,
      toStatus: "IN_STORE",
      fromLoomId: null,
      toLoomId: null,
      fromRack: "",
      toRack: beam.rack,
      remark: input.remark,
      createdAt: beam.createdAt,
    });
    return beam;
  }

  private load(input: LoadBeamInput): BeamMovement {
    const beam = this.requireBeam(input.beamId);
    if (beam.status !== "IN_STORE") {
      fail(
        "beamId",
        `${beam.beamNo} is ${beam.status === "LOADED_ON_LOOM" ? "already on a loom" : "not in store"}`,
      );
    }
    if (!this.looms.some((l) => l.id === input.loomId)) fail("loomId", "Select a loom");
    // BUSINESS RULE PENDING CONFIRMATION: how many beams one loom may carry (ground + border…)
    // is not enforced.
    return this.move(beam, "LOADED", input.date, "LOADED_ON_LOOM", input.loomId, "", input.remark);
  }

  private move(
    beam: Beam,
    kind: BeamMovementKind,
    date: string,
    toStatus: BeamStatus,
    toLoomId: string | null,
    rack: string,
    remark: string,
  ): BeamMovement {
    if (!isIsoDate(date)) fail("date", "Enter a valid date");
    const last = this.movements.filter((m) => m.beamId === beam.id).at(-1);
    if (last && date < last.date)
      fail("date", `Date cannot be before the last movement (${last.date})`);
    const movement: BeamMovement = {
      id: this.nextId("mv"),
      number: this.nextNumber(kind),
      beamId: beam.id,
      kind,
      date,
      fromStatus: beam.status,
      toStatus,
      fromLoomId: beam.loomId,
      toLoomId,
      fromRack: beam.rack,
      toRack: rack.trim(),
      remark: remark.trim(),
      createdAt: new Date().toISOString(),
    };
    beam.status = toStatus;
    beam.loomId = toLoomId;
    beam.rack = rack.trim();
    this.movements.push(movement);
    return movement;
  }

  private requireBeam(id: string): Beam {
    const beam = this.beams.find((b) => b.id === id);
    if (!beam) return fail("beamId", "Select a beam");
    return beam;
  }

  private beam(id: string): Beam {
    const beam = this.beams.find((b) => b.id === id);
    if (!beam) throw new Error(`Unknown beam ${id}`);
    return beam;
  }

  private loomName(id: string | null): string {
    return id ? (this.looms.find((l) => l.id === id)?.name ?? "—") : "";
  }

  private nextNumber(kind: BeamMovementKind): string {
    this.counters[kind] += 1;
    return `${PREFIX[kind]}/${String(this.counters[kind]).padStart(4, "0")}`;
  }

  private nextId(prefix: string): string {
    this.seq += 1;
    return `${prefix}-${Date.now().toString(36)}-${this.seq}`;
  }
}
