/**
 * Production (Rapier) frontend contracts.
 *
 * These types are the boundary between the UI and a ProductionService. Today they are
 * served by the in-memory demo adapter; a future Supabase implementation must return the
 * same shapes. Every derived value on a *Row type (balances, statuses, amounts) is a
 * PREVIEW: FINAL BACKEND MUST RECALCULATE AND VALIDATE IT.
 */

/** Calendar date, ISO `YYYY-MM-DD`. Never a locale-formatted string. */
export type IsoDate = string;

/** Lifecycle of a document. Separate from the operational (business) status. */
export type DocumentStatus = "DRAFT" | "POSTED" | "CANCELLED";

/** Operational status confirmed by the source screens. */
export type OperationalStatus = "Pending" | "Close" | "Clear";

// ---------------------------------------------------------------------------
// Master data (read-only here; later served by the canonical Supabase Masters)
// ---------------------------------------------------------------------------

export type MasterOption = { id: string; code: string; name: string };

export type Company = MasterOption;
export type Unit = MasterOption & { companyId: string };
export type Warehouse = MasterOption;
export type Party = MasterOption & { kind: "customer" | "job_work" };
export type Item = MasterOption & { category: string };
export type Yarn = MasterOption & { productType: string };
export type Machine = MasterOption & { unitId: string };
export type Beam = MasterOption;
export type Grade = MasterOption;
export type SalesOrder = MasterOption & { partyId: string; orderDate: IsoDate };

export type ProductionMasters = {
  companies: Company[];
  units: Unit[];
  warehouses: Warehouse[];
  parties: Party[];
  items: Item[];
  yarns: Yarn[];
  machines: Machine[];
  beams: Beam[];
  grades: Grade[];
  salesOrders: SalesOrder[];
  /** Placeholder list until the real stock statuses are confirmed. */
  stockStatuses: string[];
  /** Placeholder list until the real conversion types are confirmed. */
  conversionTypes: string[];
};

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

type DocumentBase = {
  id: string;
  /** Demo number (e.g. JCO/0001). FINAL DOCUMENT NUMBERING WILL BE GENERATED BY BACKEND. */
  number: string;
  date: IsoDate;
  documentStatus: DocumentStatus;
  remark: string;
  createdAt: string;
};

export type JobOrderInput = {
  date: IsoDate;
  orderPartyId: string;
  salesOrderId: string;
  partyOrderNo: string;
  itemId: string;
  yarnId: string;
  qty: number;
  rate: number;
  remark: string;
};
export type JobOrder = DocumentBase & Omit<JobOrderInput, "date" | "remark">;
export type JobOrderRow = JobOrder & {
  partyName: string;
  salesOrderNo: string;
  itemName: string;
  yarnName: string;
  amount: number;
};

export type YarnIssueInput = {
  date: IsoDate;
  jobOrderId: string;
  warehouseId: string;
  unitId: string;
  yarnId: string;
  qty: number;
  rate: number;
  remark: string;
};
export type YarnIssue = DocumentBase & Omit<YarnIssueInput, "date" | "remark">;
export type YarnIssueRow = YarnIssue & {
  jobOrderNo: string;
  partyName: string;
  warehouseName: string;
  unitName: string;
  yarnName: string;
  amount: number;
  returnedQty: number;
  /** Issue Qty − returns. */
  outstandingQty: number;
};

export type YarnReturnInput = {
  date: IsoDate;
  yarnIssueId: string;
  qty: number;
  remark: string;
};
export type YarnReturn = DocumentBase & Omit<YarnReturnInput, "date" | "remark">;
export type YarnReturnRow = YarnReturn & {
  issueNo: string;
  jobOrderId: string;
  jobOrderNo: string;
  partyName: string;
  productType: string;
  yarnName: string;
  issueQty: number;
  amount: number;
};

export type JobCardAdjustment = { id: string; date: IsoDate; qty: number; reason: string };

export type JobCardInput = {
  date: IsoDate;
  jobOrderId: string;
  partyId: string;
  cardNo: string;
  itemId: string;
  yarnId: string;
  machineId: string;
  unitId: string;
  issuedQty: number;
  remark: string;
};
export type JobCard = DocumentBase &
  Omit<JobCardInput, "date" | "remark"> & { adjustments: JobCardAdjustment[] };
export type JobCardRow = JobCard & {
  jobOrderNo: string;
  salesOrderNo: string;
  partyName: string;
  itemName: string;
  yarnName: string;
  machineName: string;
  unitName: string;
  /** Daily production + job card receipts. */
  receivedQty: number;
  adjustmentQty: number;
  /** Issued − Received − Adjustment. */
  balanceQty: number;
  status: OperationalStatus;
};

export type JobCardAdjustmentInput = {
  jobCardId: string;
  date: IsoDate;
  qty: number;
  reason: string;
};

export type DailyProductionLineInput = {
  jobCardId: string;
  qty: number;
  saleRate: number;
  pickRate: number;
  rate: number;
};
export type DailyProductionInput = {
  date: IsoDate;
  warehouseId: string;
  unitId: string;
  receiveType: "DAILY PRODUCTION";
  remark: string;
  lines: DailyProductionLineInput[];
};
export type DailyProductionLine = DailyProductionLineInput & { id: string };
export type DailyProduction = DocumentBase &
  Omit<DailyProductionInput, "date" | "remark" | "lines"> & { lines: DailyProductionLine[] };
export type DailyProductionRow = DailyProduction & {
  warehouseName: string;
  unitName: string;
  lineCount: number;
  totalQty: number;
  totalAmount: number;
};

/** One production line with its job card context, for the report. */
export type DailyProductionLineRow = {
  lineId: string;
  productionId: string;
  receiveNo: string;
  date: IsoDate;
  jobCardId: string;
  jobChallanNo: string;
  jobOrderNo: string;
  salesOrderNo: string;
  partyId: string;
  partyName: string;
  itemId: string;
  itemCode: string;
  itemName: string;
  category: string;
  yarnId: string;
  yarnName: string;
  machineId: string;
  machineName: string;
  unitId: string;
  unitName: string;
  companyId: string;
  qty: number;
  saleRate: number;
  pickRate: number;
  rate: number;
  amount: number;
};

export type JobCardReceiptInput = {
  date: IsoDate;
  jobCardId: string;
  unitId: string;
  beamId: string | null;
  receiveQty: number;
  saleQty: number;
  stockQty: number;
  stockStatus: string;
  pickRate: number;
  remark: string;
};
export type JobCardReceipt = DocumentBase & Omit<JobCardReceiptInput, "date" | "remark">;
export type JobCardReceiptRow = JobCardReceipt & {
  jobChallanNo: string;
  jobOrderId: string;
  jobOrderNo: string;
  salesOrderNo: string;
  itemName: string;
  yarnName: string;
  partyName: string;
  cardNo: string;
  unitName: string;
  machineName: string;
  beamName: string;
  amount: number;
};

/** Outward processing (Butta Cutting and Mill) share one issue/receive shape. */
export type OutwardProcess = "butta" | "mill";

export type OutwardIssueInput = {
  date: IsoDate;
  /** Butta Cutting issues from a warehouse; the Mill issue screen has no warehouse field. */
  warehouseId: string | null;
  partyId: string;
  jobOrderId: string;
  itemId: string;
  yarnId: string;
  qty: number;
  metres: number;
  remark: string;
};
export type OutwardIssue = DocumentBase &
  Omit<OutwardIssueInput, "date" | "remark"> & { process: OutwardProcess };
export type OutwardIssueRow = OutwardIssue & {
  warehouseName: string;
  partyName: string;
  jobOrderNo: string;
  itemName: string;
  yarnName: string;
  receivedQty: number;
  balanceQty: number;
  status: OperationalStatus;
};

export type OutwardReceiptInput = {
  date: IsoDate;
  issueId: string;
  warehouseId: string;
  receiveQty: number;
  metres: number;
  saleQty: number;
  stockQty: number;
  stockStatus: string;
  rate: number;
  remark: string;
};
export type OutwardReceipt = DocumentBase &
  Omit<OutwardReceiptInput, "date" | "remark"> & { process: OutwardProcess };
export type OutwardReceiptRow = OutwardReceipt & {
  issueNo: string;
  warehouseName: string;
  partyName: string;
  jobOrderId: string;
  jobOrderNo: string;
  itemName: string;
  yarnName: string;
  amount: number;
};

export type FabricTransferInput = {
  date: IsoDate;
  fromWarehouseId: string;
  toWarehouseId: string;
  jobCardId: string | null;
  itemId: string;
  yarnId: string;
  qty: number;
  remark: string;
};
export type FabricTransfer = DocumentBase & Omit<FabricTransferInput, "date" | "remark">;
export type FabricTransferRow = FabricTransfer & {
  fromWarehouseName: string;
  toWarehouseName: string;
  jobCardNo: string;
  itemName: string;
  yarnName: string;
};

export type CuttingInput = {
  date: IsoDate;
  salesOrderId: string;
  jobOrderId: string;
  itemId: string;
  yarnId: string;
  gradeId: string;
  qty: number;
  remark: string;
};
export type Cutting = DocumentBase & Omit<CuttingInput, "date" | "remark">;
export type CuttingRow = Cutting & {
  salesOrderNo: string;
  jobOrderNo: string;
  itemName: string;
  yarnName: string;
  gradeName: string;
};

export type ConversionOutLineInput = {
  jobOrderId: string;
  itemId: string;
  yarnId: string;
  unitId: string;
  boxNo: string;
  qty: number;
  remark: string;
};
/** PENDING FINAL STOCK-IN SCREEN SPECIFICATION: generic fields only. */
export type ConversionInLineInput = { itemId: string; unitId: string; qty: number; remark: string };
export type FabricConversionInput = {
  date: IsoDate;
  conversionType: string;
  warehouseId: string;
  convertBy: string;
  productName: string;
  /** Demo option: require Stock Out total = Stock In total. */
  quantityPreserving: boolean;
  remark: string;
  stockOut: ConversionOutLineInput[];
  stockIn: ConversionInLineInput[];
};
export type FabricConversion = DocumentBase &
  Omit<FabricConversionInput, "date" | "remark" | "stockOut" | "stockIn"> & {
    stockOut: (ConversionOutLineInput & { id: string })[];
    stockIn: (ConversionInLineInput & { id: string })[];
  };
export type FabricConversionRow = FabricConversion & {
  warehouseName: string;
  totalOutQty: number;
  totalInQty: number;
  differenceQty: number;
};

// ---------------------------------------------------------------------------
// Kind map: one list/create contract for every document type
// ---------------------------------------------------------------------------

export type ProductionDocumentMap = {
  jobOrder: { row: JobOrderRow; input: JobOrderInput };
  yarnIssue: { row: YarnIssueRow; input: YarnIssueInput };
  yarnReturn: { row: YarnReturnRow; input: YarnReturnInput };
  jobCard: { row: JobCardRow; input: JobCardInput };
  dailyProduction: { row: DailyProductionRow; input: DailyProductionInput };
  jobCardReceipt: { row: JobCardReceiptRow; input: JobCardReceiptInput };
  buttaIssue: { row: OutwardIssueRow; input: OutwardIssueInput };
  buttaReceipt: { row: OutwardReceiptRow; input: OutwardReceiptInput };
  millIssue: { row: OutwardIssueRow; input: OutwardIssueInput };
  millReceipt: { row: OutwardReceiptRow; input: OutwardReceiptInput };
  fabricTransfer: { row: FabricTransferRow; input: FabricTransferInput };
  cutting: { row: CuttingRow; input: CuttingInput };
  fabricConversion: { row: FabricConversionRow; input: FabricConversionInput };
};

export type ProductionKind = keyof ProductionDocumentMap;
export type RowOf<K extends ProductionKind> = ProductionDocumentMap[K]["row"];
export type InputOf<K extends ProductionKind> = ProductionDocumentMap[K]["input"];

export type DateRange = { from: IsoDate; to: IsoDate };

export type ProductionDraft<K extends ProductionKind = ProductionKind> = {
  id: string;
  kind: K;
  savedAt: string;
  input: InputOf<K>;
};

export type TraceStage = {
  stage: string;
  documents: { id: string; number: string; date: IsoDate }[];
};
