/**
 * ItemMasterDemoService — FRONTEND PROTOTYPE ADAPTER. In-memory only: nothing reaches
 * Supabase or localStorage and a page reload restores the fixtures.
 * FINAL ITEM CODE WILL BE GENERATED BY BACKEND; codes here are demo only.
 */
import type {
  ItemInput,
  ItemMasterLookups,
  ItemRecord,
  ItemSummary,
  LookupOption,
} from "@/features/item-master/types/item-master";
import {
  ItemValidationError,
  type ItemMasterService,
} from "@/features/item-master/services/item-master-service";
import { validateItem } from "@/features/item-master/utils/item-model";
import {
  demoItemRecords,
  ITEM_MASTER_DEMO_LOOKUPS,
} from "@/features/item-master/demo/item-master-demo-data";

const nameOf = (list: LookupOption[], id: string) => list.find((x) => x.id === id)?.name ?? "";

export class ItemMasterDemoService implements ItemMasterService {
  readonly mode = "demo" as const;
  private items: ItemRecord[] = demoItemRecords();
  private counter = 0;

  async getLookups(): Promise<ItemMasterLookups> {
    return structuredClone(ITEM_MASTER_DEMO_LOOKUPS);
  }

  async listItems(): Promise<ItemSummary[]> {
    const l = ITEM_MASTER_DEMO_LOOKUPS;
    return this.items
      .map((i): ItemSummary => ({
        id: i.id,
        code: i.code,
        productName: i.basic.productName,
        productType: nameOf(l.productTypes, i.basic.productTypeId),
        category: nameOf(l.categories, i.basic.categoryId),
        group: nameOf(l.groups, i.basic.groupId),
        brand: nameOf(l.brands, i.basic.brandId),
        shade: nameOf(l.shades, i.basic.shadeId),
        hsnSac: i.basic.hsnSac,
        primaryUnit: l.uoms.find((u) => u.id === i.basic.primaryUnitId)?.code ?? "",
        productStatus: nameOf(l.productStatuses, i.status.productStatusId),
        recordStatus: i.recordStatus,
        origin: i.origin,
        validFrom: i.status.validFrom,
        validTo: i.status.validTo,
        updatedAt: i.updatedAt,
        hasImage: !!i.image,
      }))
      .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt) || a.code.localeCompare(b.code));
  }

  async getItem(id: string): Promise<ItemRecord | null> {
    const item = this.items.find((i) => i.id === id);
    return item ? structuredClone(item) : null;
  }

  async saveDraft(input: ItemInput, id?: string): Promise<ItemRecord> {
    const errors = validateItem(input, "draft");
    if (Object.keys(errors).length) throw new ItemValidationError(errors);
    return this.upsert(input, id, "DRAFT");
  }

  async save(input: ItemInput, id?: string): Promise<ItemRecord> {
    const errors = validateItem(input, "save");
    if (Object.keys(errors).length) throw new ItemValidationError(errors);
    return this.upsert(input, id, "SAVED");
  }

  async deleteDraft(id: string): Promise<void> {
    const item = this.items.find((i) => i.id === id);
    if (!item) return;
    if (item.recordStatus !== "DRAFT" || item.origin !== "session") {
      throw new Error(
        "Only drafts created in this session can be deleted. Saved items are deactivated instead.",
      );
    }
    this.items = this.items.filter((i) => i.id !== id);
  }

  private upsert(
    input: ItemInput,
    id: string | undefined,
    recordStatus: ItemRecord["recordStatus"],
  ): ItemRecord {
    const now = new Date().toISOString();
    const existing = id ? this.items.find((i) => i.id === id) : undefined;
    if (existing) {
      // One version per item in the prototype: Save Draft marks it DRAFT (not validated
      // as complete), Save marks it SAVED after full validation.
      const next: ItemRecord = {
        ...structuredClone(input),
        id: existing.id,
        code: existing.code,
        origin: existing.origin,
        createdAt: existing.createdAt,
        updatedAt: now,
        recordStatus,
      };
      this.items = this.items.map((i) => (i.id === existing.id ? next : i));
      return structuredClone(next);
    }
    this.counter += 1;
    const record: ItemRecord = {
      ...structuredClone(input),
      id: `demo-item-${Date.now().toString(36)}-${this.counter}`,
      code: `ITM/${String(this.counter).padStart(4, "0")}`,
      recordStatus,
      origin: "session",
      createdAt: now,
      updatedAt: now,
    };
    this.items = [record, ...this.items];
    return structuredClone(record);
  }
}
