/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as FeedersRouteImport } from './routes/feeders'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AdminMigrationRouteImport } from './routes/admin.migration'
import { Route as CostSheetsIndexRouteImport } from './routes/cost-sheets.index'
import { Route as CostSheetsIdRouteImport } from './routes/cost-sheets.$id'
import { Route as CostSheetsNewRouteImport } from './routes/cost-sheets.new'
import { Route as InventoryApprovalsRouteImport } from './routes/inventory.approvals'
import { Route as InventoryBeamRouteImport } from './routes/inventory.beam'
import { Route as InventoryFabricRouteImport } from './routes/inventory.fabric'
import { Route as InventoryQaRouteImport } from './routes/inventory.qa'
import { Route as InventoryReservationsRouteImport } from './routes/inventory.reservations'
import { Route as InventorySearchRouteImport } from './routes/inventory.search'
import { Route as InventoryYarnRouteImport } from './routes/inventory.yarn'
import { Route as MastersTypeRouteImport } from './routes/masters.$type'
import { Route as ProductionDailyRouteImport } from './routes/production.daily'
import { Route as ProductionJobCardsRouteImport } from './routes/production.job-cards'
import { Route as ProductionLoomsRouteImport } from './routes/production.looms'
import { Route as ProductionOrdersRouteImport } from './routes/production.orders'
import { Route as QualityInspectionRouteImport } from './routes/quality.inspection'
import { Route as QualityShadeRouteImport } from './routes/quality.shade'
import { Route as SalesCustomersRouteImport } from './routes/sales.customers'
import { Route as SalesOrdersRouteImport } from './routes/sales.orders'
import { Route as SalesOutstandingRouteImport } from './routes/sales.outstanding'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as SystemAuditRouteImport } from './routes/system.audit'
import { Route as SystemBackupRouteImport } from './routes/system.backup'
import { Route as SystemPermissionMatrixRouteImport } from './routes/system.permission-matrix'
import { Route as SystemRolesRouteImport } from './routes/system.roles'
import { Route as SystemSettingsRouteImport } from './routes/system.settings'
import { Route as SystemUsersRouteImport } from './routes/system.users'
import { Route as SystemWhatsappRouteImport } from './routes/system.whatsapp'
import { Route as ProductionRapierSplatRouteImport } from './routes/production.rapier.$'
import { Route as ProductionWarpingSplatRouteImport } from './routes/production.warping.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedersRoute = FeedersRouteImport.update({
  id: '/feeders',
  path: '/feeders',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrationRoute = AdminMigrationRouteImport.update({
  id: '/admin/migration',
  path: '/admin/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSheetsIndexRoute = CostSheetsIndexRouteImport.update({
  id: '/cost-sheets/',
  path: '/cost-sheets/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSheetsIdRoute = CostSheetsIdRouteImport.update({
  id: '/cost-sheets/$id',
  path: '/cost-sheets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSheetsNewRoute = CostSheetsNewRouteImport.update({
  id: '/cost-sheets/new',
  path: '/cost-sheets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryApprovalsRoute = InventoryApprovalsRouteImport.update({
  id: '/inventory/approvals',
  path: '/inventory/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBeamRoute = InventoryBeamRouteImport.update({
  id: '/inventory/beam',
  path: '/inventory/beam',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryFabricRoute = InventoryFabricRouteImport.update({
  id: '/inventory/fabric',
  path: '/inventory/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryQaRoute = InventoryQaRouteImport.update({
  id: '/inventory/qa',
  path: '/inventory/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryReservationsRoute = InventoryReservationsRouteImport.update({
  id: '/inventory/reservations',
  path: '/inventory/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySearchRoute = InventorySearchRouteImport.update({
  id: '/inventory/search',
  path: '/inventory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryYarnRoute = InventoryYarnRouteImport.update({
  id: '/inventory/yarn',
  path: '/inventory/yarn',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersTypeRoute = MastersTypeRouteImport.update({
  id: '/masters/$type',
  path: '/masters/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionDailyRoute = ProductionDailyRouteImport.update({
  id: '/production/daily',
  path: '/production/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionJobCardsRoute = ProductionJobCardsRouteImport.update({
  id: '/production/job-cards',
  path: '/production/job-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionLoomsRoute = ProductionLoomsRouteImport.update({
  id: '/production/looms',
  path: '/production/looms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionOrdersRoute = ProductionOrdersRouteImport.update({
  id: '/production/orders',
  path: '/production/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityInspectionRoute = QualityInspectionRouteImport.update({
  id: '/quality/inspection',
  path: '/quality/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityShadeRoute = QualityShadeRouteImport.update({
  id: '/quality/shade',
  path: '/quality/shade',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOutstandingRoute = SalesOutstandingRouteImport.update({
  id: '/sales/outstanding',
  path: '/sales/outstanding',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAuditRoute = SystemAuditRouteImport.update({
  id: '/system/audit',
  path: '/system/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemBackupRoute = SystemBackupRouteImport.update({
  id: '/system/backup',
  path: '/system/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemPermissionMatrixRoute = SystemPermissionMatrixRouteImport.update({
  id: '/system/permission-matrix',
  path: '/system/permission-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRolesRoute = SystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersRoute = SystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemWhatsappRoute = SystemWhatsappRouteImport.update({
  id: '/system/whatsapp',
  path: '/system/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRapierSplatRoute = ProductionRapierSplatRouteImport.update({
  id: '/production/rapier/$',
  path: '/production/rapier/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionWarpingSplatRoute = ProductionWarpingSplatRouteImport.update({
  id: '/production/warping/$',
  path: '/production/warping/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/feeders': typeof FeedersRoute
  '/gallery': typeof GalleryRoute
  '/reports': typeof ReportsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/cost-sheets/new': typeof CostSheetsNewRoute
  '/inventory/approvals': typeof InventoryApprovalsRoute
  '/inventory/beam': typeof InventoryBeamRoute
  '/inventory/fabric': typeof InventoryFabricRoute
  '/inventory/qa': typeof InventoryQaRoute
  '/inventory/reservations': typeof InventoryReservationsRoute
  '/inventory/search': typeof InventorySearchRoute
  '/inventory/yarn': typeof InventoryYarnRoute
  '/masters/$type': typeof MastersTypeRoute
  '/production/daily': typeof ProductionDailyRoute
  '/production/job-cards': typeof ProductionJobCardsRoute
  '/production/looms': typeof ProductionLoomsRoute
  '/production/orders': typeof ProductionOrdersRoute
  '/quality/inspection': typeof QualityInspectionRoute
  '/quality/shade': typeof QualityShadeRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/outstanding': typeof SalesOutstandingRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/system/audit': typeof SystemAuditRoute
  '/system/backup': typeof SystemBackupRoute
  '/system/permission-matrix': typeof SystemPermissionMatrixRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/whatsapp': typeof SystemWhatsappRoute
  '/cost-sheets/': typeof CostSheetsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/production/rapier/$': typeof ProductionRapierSplatRoute
  '/production/warping/$': typeof ProductionWarpingSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/feeders': typeof FeedersRoute
  '/gallery': typeof GalleryRoute
  '/reports': typeof ReportsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/cost-sheets/new': typeof CostSheetsNewRoute
  '/inventory/approvals': typeof InventoryApprovalsRoute
  '/inventory/beam': typeof InventoryBeamRoute
  '/inventory/fabric': typeof InventoryFabricRoute
  '/inventory/qa': typeof InventoryQaRoute
  '/inventory/reservations': typeof InventoryReservationsRoute
  '/inventory/search': typeof InventorySearchRoute
  '/inventory/yarn': typeof InventoryYarnRoute
  '/masters/$type': typeof MastersTypeRoute
  '/production/daily': typeof ProductionDailyRoute
  '/production/job-cards': typeof ProductionJobCardsRoute
  '/production/looms': typeof ProductionLoomsRoute
  '/production/orders': typeof ProductionOrdersRoute
  '/quality/inspection': typeof QualityInspectionRoute
  '/quality/shade': typeof QualityShadeRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/outstanding': typeof SalesOutstandingRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/system/audit': typeof SystemAuditRoute
  '/system/backup': typeof SystemBackupRoute
  '/system/permission-matrix': typeof SystemPermissionMatrixRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/whatsapp': typeof SystemWhatsappRoute
  '/cost-sheets': typeof CostSheetsIndexRoute
  '/system': typeof SystemIndexRoute
  '/production/rapier/$': typeof ProductionRapierSplatRoute
  '/production/warping/$': typeof ProductionWarpingSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/feeders': typeof FeedersRoute
  '/gallery': typeof GalleryRoute
  '/reports': typeof ReportsRoute
  '/admin/migration': typeof AdminMigrationRoute
  '/cost-sheets/$id': typeof CostSheetsIdRoute
  '/cost-sheets/new': typeof CostSheetsNewRoute
  '/inventory/approvals': typeof InventoryApprovalsRoute
  '/inventory/beam': typeof InventoryBeamRoute
  '/inventory/fabric': typeof InventoryFabricRoute
  '/inventory/qa': typeof InventoryQaRoute
  '/inventory/reservations': typeof InventoryReservationsRoute
  '/inventory/search': typeof InventorySearchRoute
  '/inventory/yarn': typeof InventoryYarnRoute
  '/masters/$type': typeof MastersTypeRoute
  '/production/daily': typeof ProductionDailyRoute
  '/production/job-cards': typeof ProductionJobCardsRoute
  '/production/looms': typeof ProductionLoomsRoute
  '/production/orders': typeof ProductionOrdersRoute
  '/quality/inspection': typeof QualityInspectionRoute
  '/quality/shade': typeof QualityShadeRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/outstanding': typeof SalesOutstandingRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/system/audit': typeof SystemAuditRoute
  '/system/backup': typeof SystemBackupRoute
  '/system/permission-matrix': typeof SystemPermissionMatrixRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/settings': typeof SystemSettingsRoute
  '/system/users': typeof SystemUsersRoute
  '/system/whatsapp': typeof SystemWhatsappRoute
  '/cost-sheets/': typeof CostSheetsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/production/rapier/$': typeof ProductionRapierSplatRoute
  '/production/warping/$': typeof ProductionWarpingSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/designs'
    | '/feeders'
    | '/gallery'
    | '/reports'
    | '/admin/migration'
    | '/cost-sheets/$id'
    | '/cost-sheets/new'
    | '/inventory/approvals'
    | '/inventory/beam'
    | '/inventory/fabric'
    | '/inventory/qa'
    | '/inventory/reservations'
    | '/inventory/search'
    | '/inventory/yarn'
    | '/masters/$type'
    | '/production/daily'
    | '/production/job-cards'
    | '/production/looms'
    | '/production/orders'
    | '/quality/inspection'
    | '/quality/shade'
    | '/sales/customers'
    | '/sales/orders'
    | '/sales/outstanding'
    | '/sales/quotations'
    | '/system/audit'
    | '/system/backup'
    | '/system/permission-matrix'
    | '/system/roles'
    | '/system/settings'
    | '/system/users'
    | '/system/whatsapp'
    | '/cost-sheets/'
    | '/system/'
    | '/production/rapier/$'
    | '/production/warping/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/designs'
    | '/feeders'
    | '/gallery'
    | '/reports'
    | '/admin/migration'
    | '/cost-sheets/$id'
    | '/cost-sheets/new'
    | '/inventory/approvals'
    | '/inventory/beam'
    | '/inventory/fabric'
    | '/inventory/qa'
    | '/inventory/reservations'
    | '/inventory/search'
    | '/inventory/yarn'
    | '/masters/$type'
    | '/production/daily'
    | '/production/job-cards'
    | '/production/looms'
    | '/production/orders'
    | '/quality/inspection'
    | '/quality/shade'
    | '/sales/customers'
    | '/sales/orders'
    | '/sales/outstanding'
    | '/sales/quotations'
    | '/system/audit'
    | '/system/backup'
    | '/system/permission-matrix'
    | '/system/roles'
    | '/system/settings'
    | '/system/users'
    | '/system/whatsapp'
    | '/cost-sheets'
    | '/system'
    | '/production/rapier/$'
    | '/production/warping/$'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/auth'
    | '/designs'
    | '/feeders'
    | '/gallery'
    | '/reports'
    | '/admin/migration'
    | '/cost-sheets/$id'
    | '/cost-sheets/new'
    | '/inventory/approvals'
    | '/inventory/beam'
    | '/inventory/fabric'
    | '/inventory/qa'
    | '/inventory/reservations'
    | '/inventory/search'
    | '/inventory/yarn'
    | '/masters/$type'
    | '/production/daily'
    | '/production/job-cards'
    | '/production/looms'
    | '/production/orders'
    | '/quality/inspection'
    | '/quality/shade'
    | '/sales/customers'
    | '/sales/orders'
    | '/sales/outstanding'
    | '/sales/quotations'
    | '/system/audit'
    | '/system/backup'
    | '/system/permission-matrix'
    | '/system/roles'
    | '/system/settings'
    | '/system/users'
    | '/system/whatsapp'
    | '/cost-sheets/'
    | '/system/'
    | '/production/rapier/$'
    | '/production/warping/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  DesignsRoute: typeof DesignsRoute
  FeedersRoute: typeof FeedersRoute
  GalleryRoute: typeof GalleryRoute
  ReportsRoute: typeof ReportsRoute
  AdminMigrationRoute: typeof AdminMigrationRoute
  CostSheetsIdRoute: typeof CostSheetsIdRoute
  CostSheetsNewRoute: typeof CostSheetsNewRoute
  InventoryApprovalsRoute: typeof InventoryApprovalsRoute
  InventoryBeamRoute: typeof InventoryBeamRoute
  InventoryFabricRoute: typeof InventoryFabricRoute
  InventoryQaRoute: typeof InventoryQaRoute
  InventoryReservationsRoute: typeof InventoryReservationsRoute
  InventorySearchRoute: typeof InventorySearchRoute
  InventoryYarnRoute: typeof InventoryYarnRoute
  MastersTypeRoute: typeof MastersTypeRoute
  ProductionDailyRoute: typeof ProductionDailyRoute
  ProductionJobCardsRoute: typeof ProductionJobCardsRoute
  ProductionLoomsRoute: typeof ProductionLoomsRoute
  ProductionOrdersRoute: typeof ProductionOrdersRoute
  QualityInspectionRoute: typeof QualityInspectionRoute
  QualityShadeRoute: typeof QualityShadeRoute
  SalesCustomersRoute: typeof SalesCustomersRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SalesOutstandingRoute: typeof SalesOutstandingRoute
  SalesQuotationsRoute: typeof SalesQuotationsRoute
  SystemAuditRoute: typeof SystemAuditRoute
  SystemBackupRoute: typeof SystemBackupRoute
  SystemPermissionMatrixRoute: typeof SystemPermissionMatrixRoute
  SystemRolesRoute: typeof SystemRolesRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  SystemUsersRoute: typeof SystemUsersRoute
  SystemWhatsappRoute: typeof SystemWhatsappRoute
  CostSheetsIndexRoute: typeof CostSheetsIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  ProductionRapierSplatRoute: typeof ProductionRapierSplatRoute
  ProductionWarpingSplatRoute: typeof ProductionWarpingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeders': {
      id: '/feeders'
      path: '/feeders'
      fullPath: '/feeders'
      preLoaderRoute: typeof FeedersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migration': {
      id: '/admin/migration'
      path: '/admin/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AdminMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-sheets/': {
      id: '/cost-sheets/'
      path: '/cost-sheets'
      fullPath: '/cost-sheets/'
      preLoaderRoute: typeof CostSheetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-sheets/$id': {
      id: '/cost-sheets/$id'
      path: '/cost-sheets/$id'
      fullPath: '/cost-sheets/$id'
      preLoaderRoute: typeof CostSheetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-sheets/new': {
      id: '/cost-sheets/new'
      path: '/cost-sheets/new'
      fullPath: '/cost-sheets/new'
      preLoaderRoute: typeof CostSheetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/approvals': {
      id: '/inventory/approvals'
      path: '/inventory/approvals'
      fullPath: '/inventory/approvals'
      preLoaderRoute: typeof InventoryApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/beam': {
      id: '/inventory/beam'
      path: '/inventory/beam'
      fullPath: '/inventory/beam'
      preLoaderRoute: typeof InventoryBeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/fabric': {
      id: '/inventory/fabric'
      path: '/inventory/fabric'
      fullPath: '/inventory/fabric'
      preLoaderRoute: typeof InventoryFabricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/qa': {
      id: '/inventory/qa'
      path: '/inventory/qa'
      fullPath: '/inventory/qa'
      preLoaderRoute: typeof InventoryQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/reservations': {
      id: '/inventory/reservations'
      path: '/inventory/reservations'
      fullPath: '/inventory/reservations'
      preLoaderRoute: typeof InventoryReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/search': {
      id: '/inventory/search'
      path: '/inventory/search'
      fullPath: '/inventory/search'
      preLoaderRoute: typeof InventorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/yarn': {
      id: '/inventory/yarn'
      path: '/inventory/yarn'
      fullPath: '/inventory/yarn'
      preLoaderRoute: typeof InventoryYarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/$type': {
      id: '/masters/$type'
      path: '/masters/$type'
      fullPath: '/masters/$type'
      preLoaderRoute: typeof MastersTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/daily': {
      id: '/production/daily'
      path: '/production/daily'
      fullPath: '/production/daily'
      preLoaderRoute: typeof ProductionDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/job-cards': {
      id: '/production/job-cards'
      path: '/production/job-cards'
      fullPath: '/production/job-cards'
      preLoaderRoute: typeof ProductionJobCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/looms': {
      id: '/production/looms'
      path: '/production/looms'
      fullPath: '/production/looms'
      preLoaderRoute: typeof ProductionLoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/orders': {
      id: '/production/orders'
      path: '/production/orders'
      fullPath: '/production/orders'
      preLoaderRoute: typeof ProductionOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/inspection': {
      id: '/quality/inspection'
      path: '/quality/inspection'
      fullPath: '/quality/inspection'
      preLoaderRoute: typeof QualityInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/shade': {
      id: '/quality/shade'
      path: '/quality/shade'
      fullPath: '/quality/shade'
      preLoaderRoute: typeof QualityShadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/orders': {
      id: '/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/outstanding': {
      id: '/sales/outstanding'
      path: '/sales/outstanding'
      fullPath: '/sales/outstanding'
      preLoaderRoute: typeof SalesOutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/audit': {
      id: '/system/audit'
      path: '/system/audit'
      fullPath: '/system/audit'
      preLoaderRoute: typeof SystemAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/backup': {
      id: '/system/backup'
      path: '/system/backup'
      fullPath: '/system/backup'
      preLoaderRoute: typeof SystemBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/permission-matrix': {
      id: '/system/permission-matrix'
      path: '/system/permission-matrix'
      fullPath: '/system/permission-matrix'
      preLoaderRoute: typeof SystemPermissionMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/roles': {
      id: '/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof SystemRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users': {
      id: '/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/whatsapp': {
      id: '/system/whatsapp'
      path: '/system/whatsapp'
      fullPath: '/system/whatsapp'
      preLoaderRoute: typeof SystemWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/rapier/$': {
      id: '/production/rapier/$'
      path: '/production/rapier/$'
      fullPath: '/production/rapier/$'
      preLoaderRoute: typeof ProductionRapierSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/warping/$': {
      id: '/production/warping/$'
      path: '/production/warping/$'
      fullPath: '/production/warping/$'
      preLoaderRoute: typeof ProductionWarpingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  DesignsRoute: DesignsRoute,
  FeedersRoute: FeedersRoute,
  GalleryRoute: GalleryRoute,
  ReportsRoute: ReportsRoute,
  AdminMigrationRoute: AdminMigrationRoute,
  CostSheetsIdRoute: CostSheetsIdRoute,
  CostSheetsNewRoute: CostSheetsNewRoute,
  InventoryApprovalsRoute: InventoryApprovalsRoute,
  InventoryBeamRoute: InventoryBeamRoute,
  InventoryFabricRoute: InventoryFabricRoute,
  InventoryQaRoute: InventoryQaRoute,
  InventoryReservationsRoute: InventoryReservationsRoute,
  InventorySearchRoute: InventorySearchRoute,
  InventoryYarnRoute: InventoryYarnRoute,
  MastersTypeRoute: MastersTypeRoute,
  ProductionDailyRoute: ProductionDailyRoute,
  ProductionJobCardsRoute: ProductionJobCardsRoute,
  ProductionLoomsRoute: ProductionLoomsRoute,
  ProductionOrdersRoute: ProductionOrdersRoute,
  QualityInspectionRoute: QualityInspectionRoute,
  QualityShadeRoute: QualityShadeRoute,
  SalesCustomersRoute: SalesCustomersRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SalesOutstandingRoute: SalesOutstandingRoute,
  SalesQuotationsRoute: SalesQuotationsRoute,
  SystemAuditRoute: SystemAuditRoute,
  SystemBackupRoute: SystemBackupRoute,
  SystemPermissionMatrixRoute: SystemPermissionMatrixRoute,
  SystemRolesRoute: SystemRolesRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  SystemUsersRoute: SystemUsersRoute,
  SystemWhatsappRoute: SystemWhatsappRoute,
  CostSheetsIndexRoute: CostSheetsIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  ProductionRapierSplatRoute: ProductionRapierSplatRoute,
  ProductionWarpingSplatRoute: ProductionWarpingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
